### ISSUE TITLE
When a server returns SymbolInformation[] in textDocument/documentSymbol, show the containerName

### ISSUE THREAD

**Issue by genericptr** [sublimelsp/LSP#1172]
Document symbols can and should support the containerName in the UI.

https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_documentSymbol

`/**
	The name of the symbol containing this symbol. This information is for
	 user interface purposes (e.g. to render a qualifier in the user interface
	 if necessary). It can't be used to re-infer a hierarchy for the document
	 symbols.
	 */
	containerName?: string;`

For example something like this would be helpful to give context to the symbol without affecting the filtering behavior. 

![Screen_Shot_2020-06-30_at_12 16 15_PM](https://user-images.githubusercontent.com/10937186/86125641-35ccc980-bb07-11ea-9fbf-e62eb5eb6dc8.png)

**Comment by rwols** [comment]
My problem here is that different languages use different separator tokens.

For C++ (maybe Rust too?) the separator token is `::`
For JSON the separator token is `/` (to make it look like a [JSON pointer](https://tools.ietf.org/html/rfc6901)).
For JS the separator is `.` I'm assuming.

A neutral separator could be
* `/` to make the item look like a "file hierarchy"
* ` ` (a space) to make the items visually separated by a space

I'm currently leaning towards `/` as it feels familiar with CTRL+P.

**Comment by genericptr** [comment]
We really need minihtml to make this world properly.

can we use tabs to separate them? what about | ? -> comes to mind also. I have not string opinion I guess but we should lobby for minihtml as a better solution.

**Comment by rchl** [comment]
If we join parent symbol with current symbol then that will affect filtering also.
Would that be something we want our should we not join?

Unless we want to show the joined path in subfield in which case that will probably not affect filtering

**Comment by rwols** [comment]
I'm not sure what minihtml can bring to the table here.

I'm talking about the following problem:

Given that I have a list of "names":
```
["MyNamespace", "CMyClass", "EMyNestedEnum"]
```
I'm assuming for Pascal it'd be best to render it in the quick panel as
```
MyNamespace.CMyClass.EMyNestedEnum
```
If this were JSON, it'd be most natural to render it as
```
MyNamespace/CMyClass/EMyNestedEnum
```
And for C++ it'd be best to render it as
```
MyNamespace::CMyClass::EMyNestedEnum
```

**Comment by rchl** [comment]
If we want to join the we should find some generic symbol (some utf8 for example) that would represent descendants well. Nothing that matches any particular language as that would get confusing for other languages.

**Comment by genericptr** [comment]
You're talking about showing the entire hierarchy. Honestly that may present its own sets of problems given how long the string could be become (maybe expose this as an option?) I don't think this is really syntax question but rather a visual design question.

What about emojis? :)

**Comment by genericptr** [comment]
> If we want to join the we should find some generic symbol (some utf8 character for example) that would represent descendants well. Nothing that matches any particular language as that would get confusing for other languages.

I agree. Something like • would be good enough for me. Or emojis like ▶️ perhaps, but I'm not sure if those are allowed. I mentioned minihtml because I would prefer some smaller but different style text, kind of like a sub caption with a background color maybe even.

**Comment by rwols** [comment]
We could be absolute nerds and use `⊃` ("is superset of")

**Comment by rwols** [comment]
After playing around with this a bit I think it’s better if the flattened hierarchy is in the first row (so it influences the filtering), and if the separator is always `/`.

**Comment by genericptr** [comment]
but we don't want to filter the container name do we? That could interfere with searching potentially. Also the first rows text is larger so this long strings will cause truncating/clipping and maybe make the actual symbol name hard to see. Maybe consider making this an option.

<img width="303" alt="Screen Shot 2020-07-18 at 9 03 31 AM" src="https://user-images.githubusercontent.com/10937186/87842379-4dad9700-c8d6-11ea-9289-e205e104f40e.png">

**Comment by rchl** [comment]
Exactly, it would potentially make filtering harder as when looking for ParentB in your example, you would also get results for all symbols that have it in inheritance path. So the initially selected one might not be the one you want, requiring more effort from the user to select the correct one.

It might be better to show the full path in the second row so that it doesn't affect the filtering. Disadvantage is that that would make results take more space.

**Comment by rwols** [comment]
OK, the majority has decided ;)

vscode-json:

![Screenshot from 2020-07-18 11-37-29](https://user-images.githubusercontent.com/2431823/87849734-21504580-c8eb-11ea-8ac6-0f56813a8714.png)

clangd:

![Screenshot from 2020-07-18 11-37-47](https://user-images.githubusercontent.com/2431823/87849740-31682500-c8eb-11ea-9d1c-0316d4b6bbe6.png)

**Comment by jwortmann** [comment]
I would suggest `>` surrounded by spaces for the separator symbol, i.e. `ParentA > ParentB > ParentC`. That's often used in e.g. website navigation to display a hierarchy.

**Comment by genericptr** [comment]
Looks good but I'm not so thrilled with the 3 lines now since we can see fewer items now. I assume they are going to add icons the quick panel eventually but for now that's just lots of wasted space. Could it be an option to add the symbol kind as a prefix to the container name with a space or some other separator symbol? Since ST4 they really trimmed down the list height and on my laptop I can only see a 3-4 symbols sometimes.

**Comment by jwortmann** [comment]
The quick panel could be replaced with a ListInputHandler, which is more compact. Only the labels for the items are in the list in that case, and additional information can be shown at the bottom of the widget (supporting minihtml).

**Comment by rwols** [comment]
But that would require to put the command in a .sublime-commands file, in which case it'll show up in the command palette, which is not ideal.

Highly off topic because you're not on Discord, but I made a basic [LSP-Julia](https://github.com/sublimelsp/LSP-Julia) helper package. Though I don't program in Julia myself, and there's probably a bunch of things wrong with the setup. Are you interested in taking over maintenance @jwortmann ? Note that it's ST4-only.

**Comment by jwortmann** [comment]
Your LSP-julia package is most likely outdated, because I already made one with lots of features at https://github.com/jwortmann/LSP-julia 😉 
Currently it uses the old LSP API. I'm planning to update it to the new API, but only when ST 4 comes publicly available because I would like to test it first and I'm... well, kind of still on my evaluation period for Sublime Text. I think I would put in on Package Control then for ST 4 exclusive, when the API calls have been updated.

**Comment by rwols** [comment]
Excellent, do you want to move that repo to the sublimelsp organization? I'll send an invite regardless and see what happens.

**Comment by genericptr** [comment]
> The quick panel could be replaced with a ListInputHandler, which is more compact. Only the labels for the items are in the list in that case, and additional information can be shown at the bottom of the widget (supporting minihtml).

That sounds perfect but I don't understand the implications of what rwols said. Making the list more compact would be great since some users (like me) like to browse the list to some extent and on laptops this is going to be very limited now.

**Comment by rchl** [comment]
The HTML content can only be shown for the currently selected item though, I believe. Not sure it's a deal-breaker or not but it's probably not ideal.

**Comment by jwortmann** [comment]
> The HTML content can only be shown for the currently selected item though

That's correct, but I would see this as an advantage due to the saved space, rather than a drawback. Here is an example of a ListInputHandler in ST 3, that I made based on the guide at https://docs.sublimetext.io/guide/extensibility/plugins/input_handlers.html#providing-a-list-of-options-with-listinputhandler:

![ListInputHandler](https://user-images.githubusercontent.com/6579999/87875476-ba598c00-c9d1-11ea-9747-74fedf847be9.gif)

I'm not sure whether it's really not possible to implement as @rwols said, because the required command already exists; it's just "LSP: Document Symbols", and the ListInputHandler could be used via adding an `input` method there. The request to the language server would then be made inside its `list_items` method. But I might be wrong because I don't have a good overview about the currently used logic for "Document Symbols" in this package.

**Comment by rchl** [comment]
> > The HTML content can only be shown for the currently selected item though
> 
> That's correct, but I would see this as an advantage due to the saved space, rather than a drawback.

Depends on the use case. In this case, I'm not sure since when you are, for example, looking at three similarly named symbols and want to decide which one to navigate to, you might want to see additional information without having to select each of them separately first.

**Comment by genericptr** [comment]
> Depends on the use case. In this case, I'm not sure since when you are, for example, looking at three similarly named symbols and want to decide which one to navigate to, you might want to see additional information without having to select each of them separately first.

That could be very well be true. The extra 3rd line is really pushing it for me in terms of space. The symbol name is very short so it's wasteful to have it occupy an entire line. It's also the information I'm least interested.

**Comment by genericptr** [comment]
I just noticed something. We were talking about separator characters but SymbolInformation only has a  "containerName" field. which is a single string and doesn't actually show a hierarchy. It's going to be the servers responsibility to format this string I believe.

**Comment by rwols** [comment]
> I just noticed something. We were talking about separator characters but SymbolInformation only has a "containerName" field. which is a single string and doesn't actually show a hierarchy. It's going to be the servers responsibility to format this string I believe.

No, that `containerName` from `SymbolInformation` should be the direct parent. But you shouldn't use `SymbolInformation` because it's deprecated. Instead return a list of `DocumentSymbol` structures.

**Comment by genericptr** [comment]
Where are you seeing it's deprecated?

Not correct, it's just a string. It's intentionally for non-hierarchical symbols.

`SymbolInformation[] which is a flat list of all symbols found in a given text document. Then neither the symbol’s location range nor the symbol’s container name should be used to infer a hierarchy.`

**Comment by rwols** [comment]
You're right, looking at the spec it seems it's not deprecated. In my opinion, editors can make better use of `DocumentSymbol`, because the definition of that struct is more "strict", so we can rely upon a more coherent structure. My changes will only affect `DocumentSymbol` because I know what to expect from the protocol.

**Comment by genericptr** [comment]
The entire point of my request was to support containerName is SymbolInformation. :) It sounds like you have a better way to use DocumentSymbols but SymbolInformation is still useful and will be used by servers so it should be properly implemented.

**Comment by genericptr** [comment]
Another issue has been started about how to improve the API for us (https://github.com/sublimehq/sublime_text/issues/3489). If this gets implemented it will be great for LSP but I still stand that SymbolInformation should be properly implemented to include all relevant information.

**Comment by rwols** [comment]
See #1260

**Comment by rwols** [comment]
This seems to be fixed.

**Comment by genericptr** [comment]
What version was this fixed in?

**Comment by rwols** [comment]
I thought this was about improving textDocument/documentSymbol, but upon closer inspection this issue asks for showing the containerName for when the server returns SymbolInformation[].

**Comment by rwols** [comment]
Actually, that also already happens: https://github.com/sublimelsp/LSP/blob/b399ee2380ecb17d8ff43949f4a2b5322c869f14/plugin/symbols.py#L194

@genericptr can you describe what it is that you're missing?

**Comment by genericptr** [comment]
It's been a long time but my last comment on #1260 I think is what this was about. Basically the container name should be included where the type name is shown now. Did this get implemented yet?

**Comment by predragnikolic** [comment]
I read this issue a couple of times XD and didn't come to any conclusion.

I would closing this issue, because I am unsure of what has to be done exactly :)

LSP has code to displays the container name,
 but as noted the SymbolInformation is deprecated in favour of DocumentSymbol or WorkspaceSymbol.

**Comment by genericptr** [comment]
SymbolInformation is deprecated in the protocol itself or this package? If it's not deprecated then what I was thinking is that the container name could be shown in the symbol list (I had some screenshots to show what I was talking about).

**Comment by predragnikolic** [comment]
> SymbolInformation is deprecated in the protocol itself or this package? 

SymbolInformation is deprecated in the lsp specification. 
LSP added the logic to display the `containerName` for `SymbolInformartion`

![image](https://user-images.githubusercontent.com/22029477/192511055-43f2f557-17dd-4840-9c3e-e301c42bfac6.png)

I will close this, 
but feel free to reopen this ticket if something needs to be addressed.

**Comment by genericptr** [comment]
I see it fixed now. Thanks!
