### ISSUE TITLE
Handle diagnostics tags: "unnecessary" and "deprecated"

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#1227]
The pyright language server will emit diagnostics with an "unnecessary" tag when you have an unused argument. We currently show these diagnostics as-is. But they should have a different treatment, namely be greyed out or faded in some way.

![Screenshot from 2020-07-30 21-20-57](https://user-images.githubusercontent.com/2431823/88969584-5e381700-d2b1-11ea-9652-16edc57e3c0f.png)

**Comment by rchl** [comment]
I'll paste relevant comment from https://github.com/sublimelsp/LSP-pyright/issues/2 here

> When implementing "get code actions on selection change", I've mentioned that that behavior is not something that VSCode does in general but it's specific to some server (golsp or some other one). But we still did that regardless. So the fact that it happens for us but not in vscode is probably "by-design".

**Comment by rchl** [comment]
Those are "hint"-level diagnostics and are blue. Isn't that enough?
TS server also does the same. I think blue is a neutral-enough color for this use case.

**Comment by rwols** [comment]
> Those are "hint"-level diagnostics and are blue. Isn't that enough?

Well, I think they deserve special treatment. They're not really hints.

**Comment by rchl** [comment]
What deserves special treatment?
The hint-level diagnostics or those specific pyright diagnostics that highlight unused arguments?
What about typescript's "unused argument" diagnostics that behave pretty much the same?
What about other hint-level diagnostics that are not related to unused arguments?

**Comment by rwols** [comment]
The "unnecessary" tag deserves special treatment.

https://microsoft.github.io/language-server-protocol/specification#diagnostic

Might as well treat the "deprecated" tag in a special way, too.

**Comment by predragnikolic** [comment]
https://discord.com/channels/280102180189634562/645268178397560865/659869938298912814
Suggestion  for "unnecessary" tag UI.

![alt ](https://cdn.discordapp.com/attachments/645268178397560865/659869938298912811/good.gif)

this solution requires a hack in the sublime theme (I lost that code, but  it I think it had "foreground_adjust": "saturation(- 100%)",)
```
{
            "name": "Used",
            "scope": "unused",
             // with foreground_adjust a theme can adjust the color of the forground
             // but for that to work you need to set a background. Which in my case is almost transparent, thanks O dat nurd for that trick :)
            "background": "#ffffff10"
        }
```
and  later i had view.add_regions(regions_key, regions, scope="unused", ...)

it would be good if view.add_regions allowed changing just the foreground color, but I think that the add_regions is overpowered, I don't know if it would  be better to  add view.add_styles(`regions_key` or `regions`, style={"foreground":  "red"}) or something like that( but that is a different topic).

Also there was someone asking a visual indication for deprecated diagnostics
https://github.com/sublimelsp/LSP/issues/895:

I had a suggestion about the UI (note the triangle)
https://github.com/sublimelsp/LSP/issues/895#issuecomment-592927151
![dasd](https://user-images.githubusercontent.com/22029477/75605181-d0c58080-5ae0-11ea-89a4-78f6ad3d7848.png)

**Comment by rchl** [comment]
Sounds like a good solution until there is proper API for this. I think it should be fairly easy to create an override for a theme? That could be explained in the readme.

**Comment by rwols** [comment]
You can change "just" the foreground color by using a supermassive mega hack where you set the color in such a way that it's one more or less (in unsigned integer value) than the actual color: https://github.com/Wramberg/TerminalView/pull/53/commits/15c908b3bf40f583357c2d389d0e3544be91b411 (https://github.com/Wramberg/TerminalView/pull/53 for the full story)

```python
def next_color(color_text):
    """
    Given a color string "#xxxxxy", returns its next color "#xxxxx{y+1}".
    """
    hex_value = int(color_text[1:], 16)
    if hex_value == 16777215:  # #ffffff
        return "#fffffe"
    else:
        return "#{}".format(hex(hex_value+1)[2:])
```

**Comment by rwols** [comment]
For "deprecated", it's I think best to use `scope=invalid.deprecated` for `add_regions`.

It's a big no for me to start generating color schemes on-the-fly. It's error-prone.

**Comment by rchl** [comment]
I meant to describe needed changes in the readme and let the user would do them himself. At least for the time being.

But did you really mean that the theme needs to be overridden @predragnikolic and not color scheme?

**Comment by jwortmann** [comment]
I don't think LSP should use some hack to override the color scheme (if I understand that correctly). So currently there seems no good way to set the foreground color or add e.g. strike through style (as suggested in the protocol) for "Deprecated", unless https://github.com/sublimehq/sublime_text/issues/817 or something similar for semantic highlighting gets implemented.

> For "deprecated", it's I think best to use scope=invalid.deprecated for add_regions

Semantically I agree, but that would result in bad visual style in my opinion. Here is an example for Monokai and Mariana (icon for `add_regions` gets `foreground` color, and underline gets `background` color if exists, otherwise `foreground` too):

![screenshot](https://user-images.githubusercontent.com/6579999/89055365-8af43900-d35a-11ea-8104-7aca5d478f24.png)

So I would suggest `comment` scope instead:

![screenshot2](https://user-images.githubusercontent.com/6579999/89055400-97789180-d35a-11ea-9cf7-7aaf3af3fb01.png)

**Comment by predragnikolic** [comment]
> But did you really mean that the theme needs to be overridden @predragnikolic and not color scheme?

@rchl sublime color scheme needs to be overridden. 

[Colore Comments](https://packagecontrol.io/packages/Colored%20Comments ) offers a generate color scheme command.
When run, it creates an override in the Packages/Colored Comments Override/ThemeName.sublime-color-scheme file.
<details>
  <summary>ThemeName.sublime-color-scheme</summary>
<pre>
{
	"rules":
	[
		{
			"background": "rgba(1,22,38, 0.1)",
			"foreground": "#FF2D00",
			"name": "[Colored Comments] Important",
			"scope": "colored.comments.color.important"
		},
		{
			"background": "rgba(1,22,38, 0.1)",
			"foreground": "#98C379",
			"name": "[Colored Comments] Deprecated",
			"scope": "colored.comments.color.deprecated"
		},
		{
			"background": "rgba(1,22,38, 0.1)",
			"foreground": "#3498DB",
			"name": "[Colored Comments] Question",
			"scope": "colored.comments.color.question"
		},
		{
			"background": "rgba(1,22,38, 0.1)",
			"foreground": "#FF8C00",
			"name": "[Colored Comments] Todo",
			"scope": "colored.comments.color.todo"
		},
		{
			"background": "rgba(1,22,38, 0.1)",
			"foreground": "#9933FF",
			"name": "[Colored Comments] Fixme",
			"scope": "colored.comments.color.fixme"
		},
		{
			"background": "rgba(1,22,38, 0.1)",
			"foreground": "#474747",
			"name": "[Colored Comments] Undefined",
			"scope": "colored.comments.color.undefined"
		}
	],
	"variables":
	{
	}
}
</pre>
</details>

Before running the command:

![Screenshot from 2020-08-01 00-14-38](https://user-images.githubusercontent.com/22029477/89081835-8e081d00-d38c-11ea-8fb0-968ad7385c34.png)

> It's a big no for me to start generating color schemes on-the-fly. It's error-prone.

Waiting for an API that would allow changing the foreground, background... instead of generating color schemes overrides on-the-fly (and potentially listening on color scheme change comands, to create new overrides for the new selected ones, and  deleting the old ones maybe to clean up when uninstalling/disabling the plugin) is not a nice solution.
 
Using DRAW_STIPPLED_UNDERLINE with a comment scope to mark something as unused sounds ok  :) 

I noticed that I like to change only the background, or foreground colors in some cases. 
For example I modified the scope for the documentHighlight to not use the underlines, instead highlight the background behind the text

![image](https://user-images.githubusercontent.com/22029477/89082517-88abd200-d38e-11ea-9edf-913b4940c9a4.png)

**Comment by rchl** [comment]
Regardless of what we do here, we should figure out what would be a good way to support that in core.

For "unused" I guess some scope or something that will make the currently used color partially transparent would work?

**Comment by rwols** [comment]
Fixed by https://github.com/sublimelsp/LSP/pull/1588.

**Comment by jwortmann** [comment]
By the way, ST4 apparently already has the functionality built-in to automatically dim the foreground color dependent on the scope and color scheme. It is used to draw invisible control characters and unicode whitespace. Here is a screenshot where I added such a character in different scopes, with an unmodified Mariana color scheme:

![mariana](https://user-images.githubusercontent.com/6579999/121382543-ffb6dd00-c946-11eb-84b3-681f2e64d00f.png)

This would be really great to use for the `unnecessary` tag, to allow dimmed, but still different colors dependent on whether it describes an unused function parameter or a normal variable. They just need to add an API endpoint for it to the `View.add_regions` function...
