### ISSUE TITLE
When the completion docs have syntax highlighting highlighted with mdpopups, pressing up or down on the keyboard makes the AC disappear

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#1287]
When the completion docs have syntax highlighting highlighted with mdpopups, pressing up or down on the keyboard makes the AC disappear.

For example, try showing completion docs for `dict.get` with LSP-pyright, and then press the down arrow on the keyboard.

My initial hunch is that this is because mdpopups renders highlighting into a hidden output panel, but I can only guess at this point.

**Comment by rchl** [comment]
Can't reproduce here with LSP-typescript. Documentation is using markdown and changing selected item doesn't close the AC popup:
![Screenshot 2020-09-02 at 00 04 24](https://user-images.githubusercontent.com/153197/91910741-dda17780-ecaf-11ea-9a73-60a4ca7673b4.png)

Previously the issue with AC popup closing was due to triggering the popup update on the non-main thread.

**Comment by rchl** [comment]
OK, I can reproduce with pyright but it only reproduces after showing completions right after typing the dot. So in this state:

![Uploading Screenshot 2020-09-02 at 08.57.17.png…]()

Also, triggering completions manually with ctrl+space, at the same spot, doesn't reproduce.

**Comment by rwols** [comment]
You're right. I cannot repro this by manually invoking auto-complete. Very odd indeed. And as you say it also doesn't reproduce when the auto-complete widget is shown due to a word completion.

**Comment by rchl** [comment]
This doesn't reproduce anymore in 4087 for me (assuming I'm testing properly).

**Comment by rwols** [comment]
Neither can I. Must have been some obscure ST bug :)
