### ISSUE TITLE
Show server command errors in an error dialog when running a code action

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#1333]
**Is your feature request related to a problem? Please describe.**
When running a code action of the "command" kind, it's hard to see what happened when the server returns an error response.

**Describe the solution you'd like**
When an error response is returned, show it with `sublime.error_message`.

**Describe alternatives you've considered**
Maybe print it to the status bar. But, users are engaged in this action already, so it's OK to show a popup dialog I think.

**Additional context**

This shows in the log panel, and it is currently the *only* way to figure out what happened.
```
:: --> clangd workspace/executeCommand(11): {'arguments': [{'file': 'file:///home/raoul/xxx.h', 'selection': {'end': {'line': 62, 'character': 19}, 'start': {'line': 62, 'character': 19}}, 'tweakID': 'DefineOutline'}], 'title': 'Move function body to out-of-line.', 'command': 'clangd.applyTweak'}
:: <~~ clangd 11: {'message': "Couldn't find a suitable implementation file.", 'code': -32001}
```

**Comment by rchl** [comment]
I guess a dialog might be good enough for now but it's not ideal since it blocks the whole editor (including the main thread) and also might be a bit unexpected when the command is triggered from code action.

There are many use cases where we would want to show an error message (or just an info message) of some kind and we don't have a good solution for those. I think a panel could work but probably a separate one from the diagnostics panel.

**Comment by ayoub-benali** [comment]
I agree with @rchl, there are other cases where where a status bar isn't enough and error message is too much. Since ST doesn't have a notification. LSP could setup a new panel just for notifications.
