### ISSUE TITLE
Syntax coloring in preview popup

### ISSUE THREAD

**Issue by RUSshy** [sublimelsp/LSP#1472]
Hi,

Currently there is no syntax coloring in preview popup (when you hover a type with the mouse)

![image](https://user-images.githubusercontent.com/18348637/99688607-4bc33280-2a86-11eb-807f-2e044b1dce4b.png)

**Comment by predragnikolic** [comment]
Hello, 
Can you open up that file, and open the sublime console(ctrl+\`) and type `view.settings().get('syntax')`. And copy paste the result you got?

**Comment by RUSshy** [comment]
I get:
```
>>> view.settings().get('syntax')
'Packages/Zig.tmLanguage'
```

**Comment by rchl** [comment]
It's up to the server how it "formats" the code it sends (more precisely, how it specifies that the content should be formatted). So it's likely just the server's "fault" here.

**Comment by RUSshy** [comment]
Thanks @rchl i have reported the issue on the server repo https://github.com/zigtools/zls/issues/196

**Comment by rchl** [comment]
Actually, I've just realized something that might be the reason this doesn't work.

Even if the server properly specifies that this block should be rendered in certain syntax, the markdown library that we are using has a hardcoded lists of languages and syntaxes that it supports. Since your syntax is something custom and likely not in that list, it likely is the reason why it doesn't work.

The list is here: https://github.com/facelessuser/sublime-markdown-popups/blob/master/st3/mdpopups/st_mapping.py
You can customize the list with this setting: https://facelessuser.github.io/sublime-markdown-popups/settings/#mdpopupssublime_user_lang_map

You just need to figure out the language identifier that this server is using (but it's probably `zig`).

**Comment by RUSshy** [comment]
Thanks i will give that a try, and maybe an opportunity for me to send a PR to support zig over there out of the box (there is a plugin for zig syntax https://github.com/ziglang/sublime-zig-language)

**Comment by RUSshy** [comment]
I don't understand what i have to put in my settings file

```json
	"mdpopups.sublime_user_lang_map":
	{
		"zig":
		[
			["zig"],
			["Zig"]
		]
	},
```
This doesn't work

The identifier is Zig 

![image](https://user-images.githubusercontent.com/18348637/99752053-e3a33980-2ae3-11eb-8157-7847edda11b1.png)

**Comment by rchl** [comment]
You have to specify the path to the syntax file. Something like that:
```
	"mdpopups.sublime_user_lang_map": {
		"zig": [ ["zig"], ["Packages/Zig.tmLanguage"] ]
	},
```

Although that path doesn't look correct to me. Check the exact path to the syntax file with https://github.com/sublimelsp/LSP/issues/1472#issuecomment-730650277 and put it here, skipping the `Packages/` part.

**Comment by RUSshy** [comment]
I was using my local package, i reinstalled everything from the package manager, and now it works 

```json
	"mdpopups.sublime_user_lang_map": {
		"zig": [ ["zig"], ["Zig Language/Syntaxes/Zig"] ]
	},
```

Thanks for the help!

**Comment by RUSshy** [comment]
I sent a PR here: https://github.com/facelessuser/sublime-markdown-popups/pull/113
