### ISSUE TITLE
Hide panel when showing "No diagnostics. Well done!"

### ISSUE THREAD

**Issue by ottob** [sublimelsp/LSP#1602]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see the panel with the message "No diagnostics. Well done!".
Successful actions, like when you save a file in Sublime, usually does not require feedback. Only show feedback when something unexpected happens.

**Describe the solution you'd like**
The panel should not be displayed at all if there is no diagnostics message.

**Describe alternatives you've considered**
None.

**Additional context**
Im using the gopls lsp server. ST4 4098 with LSP plugin 1.2.11

**Comment by rwols** [comment]
It used to work like that. Auto-hiding the panel. But it results in "flickering" of the panel if diagnostics appear, and then quickly disappear. This happens most obviously with servers that start linting after a save. It's best to keep the panel open once it popped up. You have two options:

1) Press <kbd>Esc</kbd> when you're done looking at the panel.
2) Set `"show_diagnostics_panel_on_save": 0` in LSP.sublime-settings so that it doesn't automatically appear in the first place (or tweak it to some number).

**Comment by ottob** [comment]
Ok, it figures that no simple solution would exists or you would have fixed it already :)

Could it be an option that autohides the panel after X (1000?) ms if there are `No diagnostics`? Couldn't that limit the flickering?
