### ISSUE TITLE
Till when should we support ST 3 and LSP-* ST 3 plugins?

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#1697]
This is an open discussion.

LSP for ST3 haven't seen any new feature updates in a long time.
The only commits that it got was to document things.

I consider LSP for ST 3 deprecated for a long time, because all the focus was moved to LSP for ST4.
So maybe we should state in the `master` branch that LSP for ST3 is no longer maintained and that they should instead switch to LSP for ST 3.

Should we drop support for LSP-* ST3 plugins and only focus on using APIs for creating LSP-* plugins for ST4 only?

**Comment by rwols** [comment]
> Should we drop support for LSP-* ST3 plugins and only focus on using APIs for creating LSP-* plugins for ST4 only?

Yes. I'm doing this in my free time and I'm not getting paid for it. Maintaining any kind of system is boring.

**Comment by rchl** [comment]
Based on the experience so far with working on `lsp-utils`-based plugins, the cost of maintaining ST3 support was close to 0 for me. So I'm not a fan of dropping support for ST3 in those.

Or at least we shouldn't just break existing ST3 users just because there is ST4 out. We could of course create ST3-specific branches and just keep working on ST4+ version only but that will leave ST3-users without server updates.

People don't upgrade right away or even make a conscious choice not to upgrade for whatever reasons. There are some examples of that in a recent thread about the ST4 update on the Sublime Forum.

Yes, we are not paid and don't have to serve anyone but we should also have a bit of compassion to those who are still on ST3 and not just cut them away.

It would be beneficial for everyone to switch to ST4 but some just can't do it. Some for valid reasons (like can't afford an upgrade but wants to stay legal).

That said, I won't defend this position with all my power. We could branch-off ST3 versions and leave at current state but we should definitively not actively break those.

**Comment by rwols** [comment]
OK, maintain ST3 if you prefer that :)
