### ISSUE TITLE
format on save doesn't seem to work with vintage

### ISSUE THREAD

**Issue by mall0cd** [sublimelsp/LSP#1725]
**Describe the bug**
When vintage is enabled and `:w` is used to save the file, lsp doesn't format the file. I have to manually do `CTRL + s`.

**To Reproduce**
1. Enable vintage and `lsp_format_on_save` 
2. Save a file with ':w'

**Expected behavior**
lsp should format the file

**Screenshots**

**Environment (please complete the following information):**
- OS:  Arch Linux
- Sublime Text version: 4107-1
- LSP version: 1.4
- Language servers used: clangd

**Comment by rwols** [comment]
If you log what command is ran with `sublime.log_commands(True)`, you can see that `:w` runs the `save` command.

For LSP we must instead run an `lsp_save` command in order to asynchronously run code-actions-on-save, and asynchronously format-on-save.

There is no way to run code asynchronously via the `on_pre_save` callback in the ST API, hence `lsp_save` exists.

**Comment by rwols** [comment]
Note that NeoVintageous allows you to map `:w` to `lsp_save`.

**Comment by mall0cd** [comment]
> Note that NeoVintageous allows you to map `:w` to `lsp_save`.
Ok thanks, will try it.
