### ISSUE TITLE
Errors in files not currently open are not reported

### ISSUE THREAD

**Issue by thomaseizinger** [sublimelsp/LSP#1868]
**Describe the bug**

I am not sure if it is a bug or a missing feature really but I noticed that I only get warnings and errors about files that are currently opened. Changing types in Rust frequently causes errors in files I haven't touched yet and are hence not open. This leads to situations in which Sublime reports "No diagnostics. Well done!" where in reality there could be hundreds of compile-errors as soon as I run clippy.

This is kind of unsettling because it means I can never trust the LSP output and always have to run clippy before I make a commit.

Is there a way of having rust-analyzer run on all the files in the project, regardless of them being open or not?

**To Reproduce**
1. Open a Rust project and modify a file that causes a compile error in another file.
2. Close a file with a compile error
3. See "No diagnostics. Well done!"

**Expected behavior**

To have errors and warnings reported across all files in the repository such that "No diagnostics. Well done!" implies a compiling state.

**Environment (please complete the following information):**
- OS: Linux 5.10.68-1-MANJARO
- Sublime Text version: 4107
- LSP version: 1.12.1
- Language servers used: rust-analyzer

**Additional context**

Using the LSP-rust-analyzer package.

**Comment by rchl** [comment]
I don't understand what you mean. I don't think we are filtering out diagnostics for files that are not open so if the server publishes those, we should still show them in the panel.

**Comment by predragnikolic** [comment]
Here is what the spec say:
https://microsoft.github.io/language-server-protocol/specification#textDocument_publishDiagnostics

**Comment by jwortmann** [comment]
I can replicate the issue with Pyright (when configured correspondingly).

I think the problem is that diagnostics are stored in the SessionBuffer. But if there is no SessionBuffer for the URI, then the diagnostic is simply ignored:

https://github.com/sublimelsp/LSP/blob/0a874943c6090f39b25910a8950641873a06fa92/plugin/core/sessions.py#L1335-L1337

And to show the diagnostics in the panel, they are collected from the SessionBuffers:

https://github.com/sublimelsp/LSP/blob/0a874943c6090f39b25910a8950641873a06fa92/plugin/documents.py#L241-L245

Therefore the diagnostics panel will only display diagnostics in open files.

**Comment by rwols** [comment]
@jvican release made, it should appear on packagecontrol.io soon, and trickle down to users :)
