### ISSUE TITLE
Error diagnostic highlight doesn't appear with semantic highlighting enabled

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1934]
**Describe the bug**

With LSP-typescript and semantic highlighting enabled, I often notice that the error highlighting don't show up in the document if a token is also highlighted by semantic highlighting.

**To Reproduce**
1. Check this line with LSP-typescript for example: https://github.com/microsoft/vscode/blob/4be6df74d4ea0c6511c42d5951df0d4f78f1cf83/extensions/typescript-language-features/src/languageFeatures/inlayHints.ts#L72-L72

**Screenshots**

The `hint` word is not marked with a squiggly line:

![Screenshot 2022-01-16 at 21 52 17](https://user-images.githubusercontent.com/153197/149677707-4035c586-6161-42a6-8fe2-6e701e4cf805.png)

**Environment (please complete the following information):**
- OS: macOS
- Sublime Text version: 4125
- LSP version: 1.15.0
- Language servers used: LSP-typescript

**Comment by jwortmann** [comment]
I believe that is a consequence from appending the modifier to the semantic token scope in https://github.com/sublimelsp/LSP/blob/de0ef67befd7d2e813ebe7fcabacdb143ff9e535/plugin/core/sessions.py#L117 (for the purpose of being able to define a color scheme rule for tokens with modifiers). In this case the region key for this token, which is derived from the scope, will be `lsp_variable.parameter.lsp meta.semantic-token.parameter.declaration.lsp`.

But when we initialize the region keys, we use only the scopes defined in our predefined mapping: https://github.com/sublimelsp/LSP/blob/de0ef67befd7d2e813ebe7fcabacdb143ff9e535/plugin/session_view.py#L118

For this case we don't have a special scope defined, only for "parameter" token without any modifier: https://github.com/sublimelsp/LSP/blob/de0ef67befd7d2e813ebe7fcabacdb143ff9e535/plugin/core/views.py#L131

I'm not sure how this can be solved in a general way, because we don't know beforehand which of the possible combinations of token types & modifiers the server will use. It might work to add all possible combinations of token types & modifiers which were announced by the server, but that would also mean a lot of unnecessary region keys.

As a quick solution, you can explicitly declare this token with a scope in LSP-typescript.sublime-settings, for example
```json
{
    "semantic_tokens": {
        "parameter.declaration": "variable.parameter.lsp"
    }
}
```

Then the corresponding region key will also be initialized. I've tested it a few times with this adjustment, and it seems to work most of the time - but for some reason still not everytime reliably. Hm, maybe there is still some unknown behavior of the region draw order by ST, that we didn't consider yet.

As a sidenote, I found an unrelated bug that we forgot to lowercase the scope name when initializing the region keys, so the don't necessarily match in a few cases.

**Comment by rchl** [comment]
Thanks for the explanation.

I would maybe use the workaround for now but I guess the same issue could apply to other types of tokens.

**Comment by Rayzeq** [comment]
It seems that it's still broken, or that there's been a regression.

**Screenshots**
![image](https://github.com/user-attachments/assets/0fa2c361-e1fc-409c-92d8-69d8741d7910)

The yellow squiggly line and the blue dotted line should underline `modules::*`

**Environment (please complete the following information)**
    OS: Linux (nixos)
    Sublime Text version: 4169
    LSP version: 2.2.0
    Language servers used: LSP-rust-analyser

**Comment by rchl** [comment]
Feel free to create a new issue with reproduction steps.
