### ISSUE TITLE
semantic highlighting tokens are not populated when using a package-provided color scheme

### ISSUE THREAD

**Issue by tercenya** [sublimelsp/LSP#2004]
**Describe the bug**
When I change to a color scheme that is not included in Sublime by default (even if it is the same scheme, just provided by a user package), semantic highlighting tokens stop being populated.

Working as intended \<aside\>TYVM for the hard work!\</aside\>:
<img width="622" alt="Screen Shot 2022-07-24 at 5 39 12 PM" src="https://user-images.githubusercontent.com/737545/180668729-1b99f301-1b36-4e82-9db6-475a2496bbbf.png">

Same scheme but not Default, not working:
<img width="555" alt="Screen Shot 2022-07-24 at 5 39 45 PM" src="https://user-images.githubusercontent.com/737545/180668741-90463124-7489-407a-81b9-20bf46e34ce2.png">

**To Reproduce**
Install packages `LSP`, `LSP-rust-analyzer` (or configure LSP by hand), set `semantic_highlighting: true`, choose color scheme Monokai.  Open a file, wait for the LSP to do its thing.  Use `Developer -> Show Scope Name` to confirm that semantic highlighting tokens are present (type: variable, parameter, etc).  Close the source file.  Extract the `Monokai.sublime-color-scheme` file from the `Color Scheme - Default.sublime-package`, and put it in a new user package.  (You can zip the package or leave it expanded, makes no difference; I changed the name to Monokai2 just to be safe).   Switch to the new Monokai color scheme.  Open the source file, wait for the LSP do its thing.  Underlining, hovers, etc, all work fine, but `Show Scope Name` reveals no semantic tokens, no semantic colors are applied.  Harrumph.

**Environment (please complete the following information):**
- OS: macOS 12.4
- Sublime Text version: 4134
- LSP version: 1.16.3
- Language servers used: `rust-analyzer 1.64.0-nightly (897a7ec 2022-07-17), rustc 1.64.0-nightly (93ffde6f0 2022-07-23)`

**Additional context**
rust-analyzer nightly has issues with rust ABI > 1.63.  Use stable, or via `LSP-rust-analyzer`, use `"settings": {"rust-analyzer.procMacro.enable": false }` to clear up those errors.   I don't see any other obvious errors in LSP Log Panel.

Changing the color scheme while the file is open can also cause Very Strange Behavior™ RE: semantic colors.  That's likely a different bug: close the source file, change the color scheme, reopen to avoid said messiness.

(edit): typos, consistent use of "scheme" not "theme".

**Comment by jwortmann** [comment]
https://lsp.sublimetext.io/customization/#semantic-highlighting should explain everything you have to do for your color scheme to enable semantic highlighting.

Color scheme files with the same filename are merged together by Sublime Text, and LSP makes use of this to provide the required rule for the built-in schemes, for example https://github.com/sublimelsp/LSP/blob/main/ColorSchemes/Monokai.sublime-color-scheme. If you change the filename for the color scheme, this doesn't work anymore.

> Changing the color scheme while the file is open can also cause Very Strange Behavior™ RE: semantic colors.

Yeah, LSP uses some "tricks" to apply the colors from semantic highlighting, because there is no real API to modify the foreground colors. Those "artifacts" you see after changing the color scheme reveal the mechanism used to apply the semantic highlighting colors. But iirc they should go away as soon as you edit the file. Note that there are some other drawbacks from not having a proper ST API to modify syntax highlighting; for example italic/bold font style won't work at all for semantic tokens.

**Comment by rchl** [comment]
It's also mentioned in the description of the `semantic_highlighting` option in the settings file.
