### ISSUE TITLE
Kill ST3 version of the documentation

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#2077]
The ST3 version of the documentation at `lsp.readthedocs.io` tends to rank higher than the current one on Google thus we should kill it.

@tomv564 I think you might be the only one that have access to that page on readthedocs.io so please help us here. :)

**Comment by predragnikolic** [comment]
One alternative solution is to put a banner at the top of the old docs with a message that it is deprecated and to point to the new docs?

**Comment by rchl** [comment]
Added a banner and pushed to st3 branch but I'm not sure how to deploy those docs.
There seems to be some webhook at https://github.com/sublimelsp/LSP/settings/hooks but I don't know if it's still doing anything...

**Comment by predragnikolic** [comment]
Take with caution the following what I am about to write 
(Because I am not sure and haven't read the docs for Read The Docs)

https://readthedocs.org/projects/lsp/builds/13051362/
To me it looks like read the docs is listening on the master branch, so each time we push to master, it will build the docs.
The good thing is that LSP for st 4 uses the `main` branch.
We could create the master branch from the st 3 branch... in my head, that looks like it would cause Read The Docs to trigger a build. Later we could delete the master branch again.

Here are some links that I need to read, before I draw any valid conclusion 
https://docs.readthedocs.io/en/stable/versions.html#tags-and-branches
https://docs.readthedocs.io/en/stable/versions.html#version-control-support-matrix

**Comment by rchl** [comment]
We can try that.
Not sure I understand how it's able to checkout `origin/master` that shouldn't exist :)

```
 git checkout --force origin/master
Note: checking out 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f05a569 updated haskell doc 
```

**Comment by rchl** [comment]
That worked. 
(Had to also update branches in https://github.com/sublimelsp/LSP/settings/environments/51262986/edit)

**Comment by predragnikolic** [comment]
👍

Can we also now remove the added master environment?https://github.com/sublimelsp/LSP/settings/environments/51262986/edit
