### ISSUE TITLE
Replace Goto Symbol on @ character as well

### ISSUE THREAD

**Issue by ssoher** [sublimelsp/LSP#2111]
I'd like `lsp_document_symbols` to be invoked when I do Goto Anything and type in an `@` character, which is the character that lists document symbols.

`lsp_document_symbols` is very nice, I would like to have it replace Sublime Text Goto Anything with the `@` character input (Invoking GoTo Anything and typing `@` shows the document symbols). Not using a dedicated keyboard shortcut for this feature is valuable to me.

**Comment by jwortmann** [comment]
Here is a workaround:

Save as a Python file into your User folder:
```python
import sublime_plugin


class LspDocumentSymbolsWrapperCommand(sublime_plugin.WindowCommand):

    def run(self):
        view = self.window.active_view()
        if view:
            view.run_command('lsp_document_symbols')
```

Add custom keybinding:
```jsonc
    {
        "keys": ["@"],
        "command": "chain",
        "args": {
            "commands": [
                ["hide_overlay"],
                ["show_overlay", {"overlay": "goto", "text": "@"}],
                ["lsp_document_symbols_wrapper"]
            ]
        },
        "context": [
            { "key": "overlay_has_focus", "operand": true },
            { "key": "overlay_name", "operand" : "goto" },
            { "key": "preceding_text", "operator": "regex_match", "operand": "^" },
            { "key": "following_text", "operator": "regex_match", "operand": "$" }
        ]
    },
```

It's a bit of a hack though (`lsp_document_symbols` is "noop" if there is no LSP running or if it doesn't have documentSymbolProvider capability).

---

I'm a bit skeptical about adding such functionality by default, because often the builtin "Goto Symbol..." is good enough or even better (many LSP servers put a lot of junk in there, like every little variable etc.). And for the vast majority of users it should be sufficient that you can just add or override the keybinding to trigger LSP's "Goto Symbol..." panel (the example key binding under *Package Settings > LSP > Key Bindings* is commented out by default).
