### ISSUE TITLE
Code actions pop-up appears as far as possible from mouse cursor location with no obvious hotkey

### ISSUE THREAD

**Issue by Slapbox** [sublimelsp/LSP#2126]
**Is your feature request related to a problem? Please describe.**

I love Sublime and the LSP addon, but the "Code actions" popup is so far from the cursor, it's really frustrating. Then after pressing it, the menu that appears is in yet a third location. I love Sublime LSP, but it's so much more inconvenient for us to fix ESLint complaints than the UI that appeared before, I think via Sublime-Linter,  which showed the ability to fix right there, where the cursor already is.

**Describe the solution you'd like**
Make code actions accessible where the cursor already is, and make the second popup appear in the same location, rather than requiring users to make a big triangle with their mouse every time there's an issue in their code

**Describe alternatives you've considered**
A hotkey, but I don't think that really addresses the issue

**Additional context**
The big triangle I draw a fifty times a day:
![image](https://user-images.githubusercontent.com/6835891/204922207-71108722-bb92-48ab-905a-70119b6206f1.png)

**Comment by rchl** [comment]
We have been showing code actions in a native popup (like a right click popup) before but current solution has advantages over that, like:
 - shows more information (icon, server name)
 - allows to filter the list

I don't think we want to introduce the old way of handling it since it would additional complexity and code to maintain.

I kinda feel that the keyboard shortcut is the solution to your issue... If you are in a editor and writing the code, I don't see why you wouldn't want to keep hands on the keyboard and quickly trigger code actions that way and then user arrows to select the correct one. Switching to mouse/trackpad like that sounds very inefficient.

That said, I understand that there are different needs and habits but we can't (or don't want) to support everyone's needs.

**Comment by Slapbox** [comment]
Thanks for your reply @rchl. 

> I don't see why you wouldn't want to keep hands on the keyboard and quickly trigger code actions that way and then use arrows to select the correct one. Switching to mouse/trackpad like that sounds very inefficient.

First, I'm not sure what hotkeys exist. Secondly, because the issues tend to be addressed after writing something, so maybe there are  3 separate spots that need addressing and it's not very quick to move from one to the next with the keyboard (not that the cursor is particularly efficient.)

If there's a hotkey to initiate the fixes and a hotkey to move to the next item to fix, that would work. Does something like that exist?

**Comment by rchl** [comment]
Keyboard shortcuts are listed in https://lsp.sublimetext.io/keyboard_shortcuts/

Shortcut for opening code actions is not by default defined. You can go into `Preferences: LSP Key Bindings` from the Command Palette and copy it over to user key binding and assign a shortcut (for example `cmd+,` or `ctrl+,` is typically used).

For navigating diagnostics quickly there is `lsp_goto_diagnostic` (which is somehow missing from the documentation) but you can also enable it manually and bind to `f8` for example. You'll find it in LSP key bindings file.

**Comment by rchl** [comment]
For example you can try those key bindings:

```jsonc
    {
        "keys": ["f8"],
        "command": "lsp_goto_diagnostic",
        "args": {"uri": "$view_uri"},
        "context": [{"key": "setting.lsp_active"}]
    },
    {
        "keys": ["shift+f8"],
        "command": "lsp_goto_diagnostic",
        "context": [{"key": "setting.lsp_active"}]
    },
    {
        "keys": ["primary+."],
        "command": "lsp_code_actions",
        "context": [{"key": "lsp.session_with_capability", "operand": "codeActionProvider"}]
    },
```

**Comment by Slapbox** [comment]
What exactly is `primary+.` in the example @rchl?

Can you also advise how can we change the primary action that is suggested with the `// Run Code Action` command? When we hover with the mouse it suggest ESLint warnings, but when we use that code action it suggests a different action from LSP-Typescript. The action in the red circle is the one that's the top action via the mouse interface (and also the action we prefer to automate with hotkeys)

![image](https://user-images.githubusercontent.com/6835891/232251918-64bc38c6-1a4b-42c6-829e-a554b406808f.png)

Thanks again for any advice you can provide!

**Comment by rchl** [comment]
`primary` maps to `command` on Mac and `control` on Windows/Linux. So it's a primary key plus comma.

I don't think you can affect the order of code actions. Which server is shown first is not really defined so it might even change from session to session.

**Comment by Slapbox** [comment]
Is there some way to assign a hotkey directly to the fix command of our choice then? Otherwise the hotkeys are pretty worthless and I think this issue should be re-opened.

**Comment by jwortmann** [comment]
> Is there some way

There could be, namely if the return value for this particular action from the servers is either directly a [Command](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#command), or an already resolved [CodeAction](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeAction) which only uses the `command`, but not the `edit` field. And the server needs to handle its command arguments in some "deterministic" way, i.e. it expects for example the cursor position or some other things that we are able to provide as a variable (see table in the link below). You can follow the docs for [Execute server commands](https://lsp.sublimetext.io/commands/#execute-server-commands) to create a key binding for the corresponding command. To see the command name and the arguments, open the LSP log panel and compare the relevant JSON communication data when you trigger this code action manually via the UI. In order to find out what the command arguments mean, this might need a bit of detective work, for example to trigger the command in different places. Or search in the server source code to find out what it expects for the arguments. Also, some servers might crash if the command is triggered in unexpected occasions, e.g. with a position on a inappropriate line. But usually the server should just refuse / return an error if that is the case.

If you couldn't follow, paste the relevant JSON from the log panel here, and we can try to figure out whether it is possible with the server and how to make a key binding for it.

In regard to the "mouse movement way is too long" problem from the opening comment, I would suggest to buy a smaller display then. Or alternatively to reduce the size of the application window. What is the line length if you fill a whole line in you first screenshot; 500 characters? Or try the `"show_code_actions": "bulb"` setting, then the trigger link for code actions will be on the left side when you hover over the gutter icon.

**Comment by rchl** [comment]
Also, do you really want a specific keybinding for a single eslint fix? Are you gonna map hundreds of other eslint fixes each to a different key? I doubt anyone could manage that.

I think you should think about some more generic solution. For example we could support showing code actions for only a specific server so that you could limit the list to just LSP-eslint code actions.

**Comment by rwols** [comment]
If you always want to do this isn’t there some formatter tool that applies these specific eslint rules with fixes?

**Comment by rchl** [comment]
Note that those particular code actions apply ignore comment and not so much fixes. So probably it wouldn't be so sound to apply those automatically.

I do wonder why you have to apply such ignore comments so often though. Maybe there is something non-optimal about your eslint setup.

**Comment by Slapbox** [comment]
Updating legacy code to comply with new rules often can't be done as a one shot operation and requires adding some ignore statements. Additionally a significant number of ESLint rules have edge cases where it is correct to ignore them.

So they're not _code_ fixes, but they are _fixes_. All the auto-fixable stuff already is fixed by the formatter. Still, a number of things need to be ignored. Eg disallow parameter reassignment - sometimes there's no way around that but it's still a good rule generally speaking and disabling the rule for the entire file is generally the wrong approach, which then means you might need to apply the rule several times in a single file if you _must_ reassign function parameters, or break some other rule in a well considered way.
