### ISSUE TITLE
Timeout for `workspace/executeCommand` requests

### ISSUE THREAD

**Issue by LDAP** [sublimelsp/LSP#2135]
**Describe the bug**
If a server does not send a response for a `workspace/executeCommand` request (e.g. because of a crash) then the status message remains until the server is restarted. This can happen for every command that is run when a completion is accepted.

**To Reproduce**
See https://github.com/eclipse/eclipse.jdt.ls/issues/2362

**Expected behavior**
A timeout should be added to clean up missing responses.

**Screenshots**
![image](https://user-images.githubusercontent.com/8215084/207022655-47523ef3-528b-48e6-a43b-76402ceb9b8d.png)

**Environment (please complete the following information):**
- OS: 6.0.12-arch1-1
- Sublime Text version: 4141
- LSP version: https://github.com/sublimelsp/LSP/commit/472187b2b9c443b5a96f861c20aeea4903fae374
- Language servers used: jdtls

**Additional context**
none

**Comment by jwortmann** [comment]
What value would you use for the timeout? A server might start some kind of background process on receiving such a request, which could last several minutes, before sending the response. Also see https://github.com/microsoft/language-server-protocol/issues/1572

I think a better solution would be to just clean up all status messages for the server when a crash is detected.

**Comment by LDAP** [comment]
With a crash I thought of an exception that did cause the server to not respond to that request (i.e. that issue I linked above). But the server is still running and accepts new requests.

For now we could disable status messages while `workspace/executeCommand` requests are running to at least keep the status bar usable after many failed requests.

**Comment by rchl** [comment]
Timeout is not the right solution.
We should be able to detect a crash and clean those.

I haven't verified it but I have a feeling that due to all response handlers being clearer on crash:

https://github.com/sublimelsp/LSP/blob/472187b2b9c443b5a96f861c20aeea4903fae374/plugin/core/sessions.py#L1878-L1878

we don't get to clean stuff in response handler:

https://github.com/sublimelsp/LSP/blob/472187b2b9c443b5a96f861c20aeea4903fae374/plugin/core/sessions.py#L2021-L2021

Also should check whether pending promises ever get resolved because if not then there is a leak in such case.

**Comment by LDAP** [comment]
I am not quite sure how we could detect crashes on the server side. We would have to check the system out and analyze the output?

**Comment by jwortmann** [comment]
> With a crash I thought of an exception that did cause the server to not respond to that request (i.e. that issue I linked above). But the server is still running and accepts new requests.

Ah, I see. But then it's still impossible for the client to distinguish between "server had an exception and won't answer" and "request is still running and will eventually send a response".

I think this must be solved on the server side. It should implement some kind of internal exception handler and send an error response when that happens. I think the correct one would be either `InternalError` (-32603), or `RequestFailed` (-32803) in that case, see [ErrorCodes](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#errorCodes).

**Comment by rchl** [comment]
> With a crash I thought of an exception that did cause the server to not respond to that request (i.e. that issue I linked above). But the server is still running and accepts new requests.

I agree that this is something that must be handled by the server.

But I feel that we also don't handle properly the case when the server crashes but haven't tested.

**Comment by LDAP** [comment]
I agree, a timeout is not the solution. Maybe just remove the status bar message since that makes ST unusable if a server misbehaves?

**Comment by rchl** [comment]
I've looked into it and saw that we are handling removal of status correctly when server crashes. We clear `_response_handlers` and the view statuses are tied `ViewProgressReporter` and `ActiveRequest` that gets deleted due to being weak references.

**Comment by jwortmann** [comment]
For the initial problem shown in the opening comment, I could imagine a possible enhancement to group the names of open requests in the status bar and show the amount as a number next to it, if there are multiple open requests of the same type. Then you would have just an increasing number, instead of completely filling the status bar, if the server maintainers don't want to fix it on their side.

For example:
* 1 open request: `workspace/executeCommand`
* 2 open requests: `workspace/executeCommand(2)`
* 123 open requests: `workspace/executeCommand(123)`
