### ISSUE TITLE
gopls crashes with 1.21.0

### ISSUE THREAD

**Issue by flumeware** [sublimelsp/LSP#2157]
**Describe the bug**
gopls crashes following LSP being update to 1.21.0

**To Reproduce**
1. Update LSP
2. Attempt to open a go project, gopls will crash

Downgrading LSP and opening the same project resolves the issue

**Environment (please complete the following information):**
- Sublime Text version: 4143
- LSP version: 1.21.0
- Language servers used: gopls

**Comment by rchl** [comment]
What exact message are you getting?

**Comment by flumeware** [comment]
![gopls-crash](https://user-images.githubusercontent.com/1830403/210177322-df6a26bb-e38b-4528-ae65-2f8d799df123.png)

# Troubleshooting: gopls
## Version
 - LSP: 1.21.0
 - Sublime Text: 4121
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "gopls"
]
```
 - shell command
```sh
gopls
```
 - selector
```
source.go
```
 - priority_selector
```
source.go
```
 - init_options
```json
{
  "experimentalWorkspaceModule": false
}
```
 - settings
```json
{}
```
 - env
```json
{}
```

## Active view
 - File name
```
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/Go/Go.sublime-syntax"
}
```
 - base scope
```
source.go
```

## LSP configuration

```json
{
  "clients": {
    "gopls": {
      "command": [
        "gopls"
      ], 
      "enabled": true, 
      "initializationOptions": {
        "experimentalWorkspaceModule": false
      }, 
      "selector": "source.go"
    }
  }
}
```
## System PATH
 - /usr/local/bin
 - /usr/bin
 - /bin

**Comment by rchl** [comment]
We've added [`textDocument.rename.prepareSupportDefaultBehavior client capability](https://github.com/sublimelsp/LSP/blob/8da6bf710f6bd41d8e3994ec5461ae7097b84e90/plugin/core/sessions.py#L349-L349). Checking with the spec I don't see anything wrong with it. I feel that the server crashes on it because it doesn't support 3.16 spec version thus doesn't see it as support field. In that case, it would be a bug in gopls.

But maybe it's already fixed in latest version of gopls and [@TerminalFi's PR](https://github.com/sublimelsp/LSP-gopls/pull/34) will fix it.

**Comment by rchl** [comment]
Actually, you are not using https://github.com/sublimelsp/LSP-gopls so I'm not sure on which version of `gopls` you are. Try upgrading to the latest one.

**Comment by flumeware** [comment]
Thanks, looks like it was the version of gopls, I had installed it using go install, but lsp-gopls resolves the issue
