### ISSUE TITLE
`force_group` argument support for `lsp_symbol_references` command

### ISSUE THREAD

**Issue by ssoher** [sublimelsp/LSP#2168]
Working in multiple groups, `lsp_symbol_references` command doesn't work across groups but instead duplicates already open files when one of the listed references is selected to open. It should have a flag to disable `force_group` setting.

**Comment by jwortmann** [comment]
For the quick panel (`"show_references_in_quick_panel": true`) it should be pretty simple to add; just pass the `force_group` argument further to
https://github.com/sublimelsp/LSP/blob/ea73d99fce5208c3166f21c69c4b9b8ae4e2017d/plugin/references.py#L122

But for the output panel, which is still the default setting, I think it's not possible to control this. Because the only thing LSP does is to set the "result_file_regex" and "result_line_regex" setting for that output view, and ST's native build result navigation takes care of the rest.

https://github.com/sublimelsp/LSP/blob/ea73d99fce5208c3166f21c69c4b9b8ae4e2017d/plugin/core/panels.py#L92-L96
