### ISSUE TITLE
How to shrink selection while lsp has "expand selection" command ?

### ISSUE THREAD

**Issue by dongguaguaguagua** [sublimelsp/LSP#2183]
I have a key binding to lsp expand regions:
```json
// LSP expand region
{
	"keys": [
		"super+alt+up"
	],
	"command": "lsp_expand_selection",
	"context": [
		{
			"key": "lsp.session_with_capability",
			"operand": "selectionRangeProvider"
		}
	]
},
```

But I can't shrink it because lsp dosn't provide a commad "shrink selection" as the opposition of "expand selection".

**Comment by rchl** [comment]
Well, I've checked VSCode and noticed that they actually provide "Shrink selection". That said, it uses data that the server returns for "Expand selection" (since server provides all parent selection ranges at once). So it's only able to shrink up to the point from which "Expand selection" was called and not further than that. And in ST that same behavior can be achieved using "Soft Undo" (CMD+U) so it seem like it would be redundant to provide specific action for that.
