### ISSUE TITLE
Do not start the server if i provide a TCP port, Sublime is a Client, not a Server starter

### ISSUE THREAD

**Issue by ryuukk** [sublimelsp/LSP#2214]
When i provide the "tcp_port", sublime text will not connect to the server, instead it'll start the server

**To Reproduce**

[app.zip](https://github.com/sublimelsp/LSP/files/10889479/app.zip)

Sample server, it only start a TCP server on port ``6969``

Use this config:

```
		"mine": {
			"enabled": true,
			"tcp_port": 6969,
			//"command": ["c:\\dev\\kdom\\projects\\lsp\\app.exe"],
			"selector": "source.d",
			"settings": {
			},
		}
```

if i comment the "command" i get this error btw:

![image](https://user-images.githubusercontent.com/44361234/222925312-82113874-79bc-4a47-a2bb-1a8453881a19.png)

**Expected behavior**

Sublime Text should initiate a TCP connection to my already open server

It should not start the server

**Environment (please complete the following information):**
- OS: Windows 10 x64
- Sublime Text version: 4143
- LSP version: 1.22.0
- Language servers used: mine, provided above

**Additional context**

Use cases:

- Compiler server that manages its own language server
- Easier to debug as a whole since i manage server lifetime completely
- language server (compiler server) that lives in my server and clients, i can close sublime windows freely

**Comment by rwols** [comment]
I agree this would be nice to have.

**Comment by weckr** [comment]
+1 for me, i use this with godot, and the editor (and so lsp) is always running when i code by the nature of the work, dont really want sublime to mess with it. That would even be tolerable but for some reason the plugin is spinning one core to 100 percent continuously. Ive tried to give it random dummy shell command like ls or something so it would let me use the lsp, and the lsp with the tcp port filled in actually works like this, but again it spins the core making it really annoying on laptop in summer...
I might look into this myself, since its python. It would be what, just checking if tcp-port setting is present and then ignoring the missing command setting and execution?

**Comment by rwols** [comment]
@weckr the place to change this is probably in https://github.com/sublimelsp/LSP/blob/31945a6b0a573935907536efacbaa482771be472/plugin/core/transports.py#L233

**Comment by weckr** [comment]
thanks, the nc way gets buggy and slow for some reason (although at this point it just may be godots lsp), so in the end I managed to hack it in somehow.

**Comment by predragnikolic** [comment]
fixed with https://github.com/sublimelsp/LSP/pull/2300
