### ISSUE TITLE
scala LSP-metals diagnostics not displaying after upgrade to 4070-1.23.0

### ISSUE THREAD

**Issue by axb21** [sublimelsp/LSP#2217]
**Describe the bug**
On a scala 3 project I'm working on, sublime auto-updated LSP to [4070-1.23.0](https://github.com/sublimelsp/LSP/releases/tag/4070-1.23.0) after a restart today. After that, diagnostics no longer displayed in the LSP diagnostics panel, even though they were correctly being returned by the metals server and compilation with SBT failed with errors.

Removing the LSP plugin and cloning 4070-1.22.0 into Packages fixes the problem: diagnostics show up as and when expected.

**To Reproduce**
I have to apologize--this caught me by surprise today and I'm on a deadline, so I haven't tried to create a minimal example, and I'm not inclined to change around which packages are installed to run tests and risk breaking my environment again. I expect the steps below would do it but I be forewarned that I haven't tried. I do know steps 3 and 4 demonstrate the bug in the context of an existing project I have.

1. Install LSP (currently 4070-1.23.0) and the LSP-metals plugin from Package Control in sublime
2. Create a new scala project and enable LSP-metals in it. Make sure your build is imported properly etc etc
3. Create a syntactically correct scala file
4. Enter some syntax errors into your file (type some gibberish)

On opening the Diagnostics panel (right-click bottom left panel icon or Ctrl-Alt-M), you'll see the cheery message "No diagnostics. Well done!" even though SBT (or whichever build tool you use) will report compile errors and if you have LSP debug logging on you'll see metals `textDocument/publishDiagnostics` messages with the correctly-diagnosed errors about your gibberish.

**Expected behavior**
The diagnostic panel should show the appropriate syntax errors created by your gibberish

**Screenshots**
N/A

**Environment (please complete the following information):**
- OS: Ubuntu 22.04.2
- Sublime Text version: 4143
- LSP version: 4070-1.23.0
- Language servers used: LSP-metals

**Additional context**
I'm happy to test things now and then if it helps.

**Comment by rchl** [comment]
I can't think of anything that could cause such issue and I'm not competent enough in scala to reproduce your issue.

Can you provide a full log from LSP: Log Panel from 1.23.0 when things are not working as expected?

**Comment by rchl** [comment]
Actually there was one diagnostics-related change related to handling of symlinks.

If you enable `log_debug` LSP setting and check ST console (not LSP console) to see if your diagnostics are being ignored.

**Comment by axb21** [comment]
OK, I've attached two files:
- [lsp-log-panel.txt](https://github.com/sublimelsp/LSP/files/10936322/lsp-log-panel.txt), which is output from the LSP Log Panel. I had a scala file opened, I typed the text "thisisnotscala" into it, and I saved the file. That change generates a compile error, and you can see from line 56 of this file that metals reports it
- [st-log.txt](https://github.com/sublimelsp/LSP/files/10936330/st-log.txt), the sublime text log after `log_debug` is set to `true` in LSP settings, and I run through a very similar exercise as what generated the previous file.

I've anonymized the contents of both these files and included only the minimal amount of information; hope you can still see what's going on.

The sublime text log consists of mostly (only?) lines like `LSP: ignoring unsuitable diagnostics for file:///A_DIRECTORY/AScalaFile.scala reason: not inside window folders`, which seems to confirm your hunch. I have no idea what a "window folder" is or how to make sure my diagnostics are in them. This does seem like a newly-introduced issue, since I can install an older version of the plugin from the git repository and diagnostics work fine.

**Comment by rchl** [comment]
Window folders are the folders that are added to the sidebar. You can programmatically check what are their (or it) paths by running `window.folders()` in the ST console.

The the of the file with errors must be contained within one of those paths for the diagnostics not to be ignored.

We always had that behavior. The only thing that should have changed is handling of symlinks. Currently those are not resolved when checking the path of the file or the folder so the check will consider the symlink paths rather than the paths the symlinks point to.

**Comment by axb21** [comment]
So, I just checked but I suppose it goes without saying that my window folders don't change as a function of which version of the plugin I have installed. 

My project is in a subdirectory of a subdirectory of...of a directory that is symlinked. That's going to be it, isn't it.

**Comment by axb21** [comment]
> My project is in a subdirectory of a subdirectory of...of a directory that is symlinked. That's going to be it, isn't it.

Yes. That's it.

I obtained the path to my project that does not include a symlinked part. I edited my sublime-project file to use this direct path with no symlinks anywhere in the chain. Poof, diagnostics work fine with the new version of the plugin. Anyone else listening, that's your work around: make sure your sublime-project file does not contain paths that are symlinks; use the "direct" paths.

I guess it's up to you whether you consider that a bug/worth fixing or not. Personally, it caused me half a day of headache and goofing around and nearly caused me to abandon the new version of this plugin, and it's definitely a semantic change from the previous version of the plugin, so :man_shrugging:

**Comment by rchl** [comment]
It's an expected change, even if it unfortunately caused you some inconvenience. The original issue that it resolved has caused me inconvenience when in a slightly different scenario when one of the folders within project folders was symlinked. See https://github.com/sublimelsp/LSP/pull/2210 for the issue and reasoning.

But just to fully understand your issue, could you post the paths of both the folders and the file when things didn't work? You can anonymize the paths but in a way that still allows to see how they related to each other and whether they are contained within each other.

I'm thinking that if both the project folders were children of some symlinked folder and the file that had issues was just a child of project folders then it should have worked because both the project folders and the file would operator on symlink paths. So I don't quite understand why it was not working. It sounds a bit like the project folders were relative to unresolved symlink paths while the file had path relative to resolved symlink. But then I wonder how was opened using resolved location since ST should use paths relative to project folders. Maybe... server responds with resolved paths on "go to definition" which makes paths get "out of sync".

BTW. I understand if you've moved on and don't want to deal with it anymore. We'll stay in a bit of mystery here but then it seems like with either solution there are cases that can fail.

**Comment by axb21** [comment]
> The original issue that it resolved has caused me inconvenience in a slightly different scenario when one of the child folders of the project folders was symlinked.

Gotcha. I haven't been tracking these issues but I'll look into that one out of curiosity; thanks for the link.

> But just to fully understand your issue, could you post the paths of both the folders and the file when things didn't work? You can anonymize the paths but in a way that still allows to see how they related to each other and whether they are contained within each other.

My situation is that I have a large-ish filesystem in a zfs pool mounted at root; let's call it `/pool/big-filesystem`.

Then on the primary hard drive of my computer, I have an overarching project folder for a project I'm working on; let's call it `/home/me/my-project`.

The directory holding the scala project that was giving me grief lives in `/pool/big-filesystem/scala-project`. However, I had it symlinked under `/home/me/my-project/scala-project`, for convenience, so that it was with my other non-code project files.

When I generated the `sublime-project` file for that project, it picked up `/home/me/my-project/scala-project` as the path. I edited that file in another text editor and changed all instances of `/home/me/my-project/scala-project` to `/pool/big-filesystem/scala-project` and that did the trick.

I don't know if that helps you sort out what's going on, but it's probably easy enough to replicate? If I had more time tonight I'd tinker with it more but I'm out of time and don't know if I'll pick it up again next week.

Thanks for your help! Now that I know what's going on it's an easy enough issue to avoid. Hopefully no one else falls into it or quickly finds this issue if they do!

**Comment by rchl** [comment]
> When I generated the `sublime-project` file for that project, it picked up `/home/me/my-project/scala-project` as the path.

Right. And that should have been file as long as the files opened within that project would be opened from `/home/me/my-project/scala-project/**` (the `view.file_name()` in ST console would have that prefix).

But as far as I understand, the opened file had the `/pool/big-filesystem/scala-project/**` prefix and I'm not sure about how that came about. My suspition is that the LSP-metals server at some point triggered opening of the file from the original location (possibly when using "go to definition" or related command).
