### ISSUE TITLE
ability to disable document_highlight_style on multiline string blocks

### ISSUE THREAD

**Issue by titoBouzout** [sublimelsp/LSP#2246]
Unless Im mistaken, it seems to me that `document_highlight_style` is causing multiline string to have a full border, which is very distracting. 

![image](https://user-images.githubusercontent.com/64156/236600707-6459e7b1-c193-42d6-8d52-4e928430dfda.png)

I have searched and couldn't find a way to disable highlighting for multiline strings. Could be possible to add a preference to avoid this?

**Comment by jfcherng** [comment]
Neither LSP-html nor LSP-typescript behave like that on my side with `"document_highlight_style": "outline",`. Those 2 servers just return empty region on a multiline string.

**Comment by predragnikolic** [comment]
Hello, 
Can you tell me what language server that is and how to reproduce it?

In the image I see the region being drawn as an outline.
I would guess that this the thing you are looking for is not for `document_highlight_style` as there is no "outline" style for document highlights.

I would guess that the region is caused by a diagnostic hint, so my best guess for now would be to suggest  the following settings. 

See what works for you:

1.Try to set `show_multiline_diagnostics_highlights` to `false`
```
// Show diagnostics spanning multiple lines in the view (as outlines).
  // See also: "diagnostics_highlight_style".
  "show_multiline_diagnostics_highlights": true,
```

2. Try to ignore displaying hint diagnostics,
set `show_diagnostics_severity_level` to `3`
```
  // Show highlights and gutter markers in the file views for diagnostics
  // with level equal to or less than:
  // none: 0 (never show)
  // error: 1
  // warning: 2
  // info: 3
  // hint: 4
  "show_diagnostics_severity_level": 4,
```

**Comment by jwortmann** [comment]
Those are really "DocumentHighlights", not diagnostics. It intentionally uses the outline if the range spans multiple lines, see https://github.com/sublimelsp/LSP/commit/940c9189c5023cf8d08d2ec121c0fd4b682339d3.

I remember that the CSS server also used to use multi-line highlights for whole selector blocks, but AFAICT it doesn't do that anymore.

I would not be against adding the ability to configure the style for multi-line highlights, but personally I also don't need it, because I use the "background" option, which doesn't have the outline for multi-line highlight regions. So I will keep out of the decision whether to add a new setting for this. In fact, I would even suggest to make "background" the only possible style and remove the setting alltogether, if Sublime's default style for the `region.<color>ish` scopes' background were not so terrible as it is. (LSP provides more suitable overrides for all of the built-in color schemes.)

**Comment by titoBouzout** [comment]
LSP TypeScript, a js file with the following code. Seems to me is highlighted when the string is a function parameter. Anyway, doesn't matter where the string is, if it is multiline, I would prefer to not have the full block highlighted.  Is really not helpful and very distracting. About the `background` from previous comment, Im not sure what are you referring exactly, but I prefer very much underline highlighting.

```js
something(
  `somethign something`,
  "something something",
  "something something",
  `
  it
  highlights
  the
  full
  block
  here
  `
);


```

**Comment by jwortmann** [comment]
I was just referring to the `"document_highlight_style": "background"` option. You can try that if you use one of the default color schemes, like Mariana or Monokai.

For the underlines, it was like that before, and there is a screenshot in https://github.com/sublimelsp/LSP/pull/1710#issuecomment-852056245 about how that looks. But feel free to prepare a PR or wait for more opinions, if this style should be added back as an option.

**Comment by titoBouzout** [comment]
Thanks, I understand,

To be clear, I do not want any kind of highlight for multiline strings. It should be completely turned off.

I prefer this 

![image](https://user-images.githubusercontent.com/64156/236709015-b6ef8ddb-015c-4d08-9b75-18509cf9ed6e.png)


Over this 

![image](https://user-images.githubusercontent.com/64156/236709098-662e554e-8635-4952-a93b-599cd80837c8.png)

Im trying to get rid of this 

![image](https://user-images.githubusercontent.com/64156/236709117-7188dfc9-ac6d-4f3a-af73-4283853d487a.png)

and also trying to get rid of this or any other kind of style for the whole multiline block.

![image](https://user-images.githubusercontent.com/64156/236709177-ffa2ae1e-0ec2-463c-934c-855bc2723667.png)

**Comment by titoBouzout** [comment]
There I sent a pull request adding a new preference https://github.com/sublimelsp/LSP/pull/2247

**Comment by jwortmann** [comment]
That's why I wrote that the default background for the `region.<color>ish` scopes is bad. I don't know what color scheme you use, but this is how it looks with built-in Monokai:

![monokai](https://user-images.githubusercontent.com/6579999/236718620-c169c7bf-3592-4e2c-ab0f-1d4820c96bf0.png)

Some people may still not like the multiline highlights, so I guess yeah, a setting to disable them could be reasonable.

**Comment by sricks** [comment]
I've had LSP-typescript running on my project for weeks, but I never noticed this document highlighting until today; coincidentally when I installed several other plugins.

I drove myself crazy trying to fix it; I'm certain this functionality wasn't working for me before.

In any case, I strongly believe this should not be a default behavior in LSP. Discoverability was extremely poor; I had to disable every single Sublime plugin, one-by-one, to find out what was causing these outlines on multi-line strings.

And it's really quite ugly for most (all?) color schemes. If someone modifies their color scheme to work with this, they probably know enough to turn on the setting. It just really does not seem useful to me.

To aid anyone else searching: This is not related to BracketHighlighter, RainbowBrackets, or any sublime settings to match or highlight the contents of bracket contents. It is not related to `match_brackets`, `match_tags`, or `match_selection`.

The cause of this border or outline on sublime text multi-line strings in Javascript or Typescript using template literal string backticks is LSP documentHighlight, which can be discovered by running the command "LSP: Toggle Log Panel".
