### ISSUE TITLE
https://lsp.readthedocs.io/ 404s

### ISSUE THREAD

**Issue by NickGeek** [sublimelsp/LSP#2284]
**Describe the bug**
The documentation at https://lsp.readthedocs.io/

**To Reproduce**
1. Go to https://lsp.readthedocs.io/

**Expected behavior**
The documentation for ST3 should load.

**Comment by rchl** [comment]
Only @tomv564 has access to that account.

**Comment by predragnikolic** [comment]
I will try to address this today.

**Comment by predragnikolic** [comment]
Ok, read the docs no longer tries to read the `master` branch for the `latest`, [instead it will read the default branch](https://docs.readthedocs.io/en/stable/tutorial/#versioning-documentation), in this case `main` for the latest, thus it wont work.


https://lsp.readthedocs.io/en/latest/ -> doesn't work, because it was build with the `main` branch.
https://lsp.readthedocs.io/en/stable/ -> it does work

**Comment by predragnikolic** [comment]
a) We could try to ping @tomv564, but something tells me that he is busy :)

b) We could write to the readthedocs support, and ask them if they could change branch that points to `latest` to the `st3` branch? 

c) WARNING! We could replace the docs on the main branch, with the docs from the `st3` branch. Let readthedocs [finish the build](https://readthedocs.org/projects/lsp/builds/13051362/) . Once the build is finished, go to https://github.com/sublimelsp/LSP/settings/hooks and disable the checkbox for `Pushes`. That way readthedocs will no longer receive notifications to trigger builds.
![image](https://github.com/sublimelsp/LSP/assets/22029477/5a5889d6-4d46-4704-9038-e43df9f748c3)
Once that is done, revert the docs for ST4 on the main branch, and move on with life.

**Comment by rchl** [comment]
I'd rather create some redirect to ST4 there instead of deploying ST3 docs.
