### ISSUE TITLE
Add `bufferSettings` key in sublime-settings for LSP settings that only apply to unsaved buffers

### ISSUE THREAD

**Issue by kylebebak** [sublimelsp/LSP#2320]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to edit `sublime-settings` files to specify `pyright` or `ruff` settings to the code in unsaved buffers, without having these settings globally override those in `pyrightconfig.json` or `ruff.toml`

**Describe the solution you'd like**

I'm not sure if this is better implemented here, in https://github.com/sublimelsp/LSP, or in the https://github.com/sublimelsp/LSP-pyright and https://github.com/sublimelsp/LSP-ruff repos

If it can be implemented in this package, I think if would be good to have a `bufferSettings` key under `initializationOptions`. These settings apply only to unsaved buffers. If not I'd be glad to open a similar issue in the LSP-ruff repo

**Describe alternatives you've considered**

With LSP-ruff I've tried a bunch of things, but can't find a way to have settings configured for unsaved buffers without these settings overriding any and all `ruff.toml` files

**Comment by jwortmann** [comment]
I don't think this is possible. Settings and initializationOptions are global, or at least per session (i.e. workspace/window/project or whatever you want to call it) via the settings in `.sublime-project` files. There is no concept of document specific or document type (URI scheme) specific settings in the protocol. For example if you open a regular file first, and after that create an unsaved buffer with Python syntax, it will be attached to the same server instance and therefore use the same settings.

The only workaround I could imagine would be to have separate server configurations for different URI schemes under the "clients" setting in LSP.sublime-settings, for example (untested with that server):
```jsonc
{
    "clients": {
        "quick-lint-js": {
            "enabled": true,
            "schemes": ["file"],
            "command": ["quick-lint-js", "--lsp-server"],
            "selector": "source.js",
            "settings": {
                // ...
            }
        },
        "quick-lint-js-for-unsaved-buffers": {
            "enabled": true,
            "schemes": ["buffer"],
            "command": ["quick-lint-js", "--lsp-server"],
            "selector": "source.js",
            "settings": {
                // ...
            }
        },
    }
}
```

This would force unsaved buffers to start a new instance of the language server, different from an already running instance for opened files in the window.

But since pyright and ruff use those LSP-* helper packages, it won't work for your usecase.

**Comment by kylebebak** [comment]
Thanks for explaining this. I didn't realize Sublime starts a separate language server process for each language server in scope in a given project. I just opened 2 Python projects and saw the following:

```
ps -ef | rg lsp

/Users/kyle/Library/Caches/Sublime Text/Package Storage/LSP-ruff/bin/python3 /Users/kyle/Library/Caches/Sublime Text/Package Storage/LSP-ruff/bin/ruff-lsp
/Users/kyle/.nvm/current/bin/node /Users/kyle/Library/Caches/Sublime Text/Package Storage/LSP-pyright/16.20.1/language-server/node_modules/pyright/langserver.index.js --stdio

/Users/kyle/Library/Caches/Sublime Text/Package Storage/LSP-ruff/bin/python3 /Users/kyle/Library/Caches/Sublime Text/Package Storage/LSP-ruff/bin/ruff-lsp
/Users/kyle/.nvm/current/bin/node /Users/kyle/Library/Caches/Sublime Text/Package Storage/LSP-pyright/16.20.1/language-server/node_modules/pyright/langserver.index.js --stdio
```

I imagined there might be no persistent LSP process running, and that each time the editor wanted to get LSP feedback it just invoked the language server in a subprocess using the CLI. But now I'm guessing that having a persistent language server process gets rid of language server startup time and reduces latency between client and server.

Thank you again! I'm going to close this.

**Comment by jwortmann** [comment]
Actually I think now that what I wrote above is not really correct. There *is* a concept for the server to request document specific settings; namely via the optional [`ConfigurationItem.scopeUri`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#configurationItem) field in the `workspace/configuration` request. But it's not implemented in this client:
https://github.com/sublimelsp/LSP/blob/663afdc01fae817fa4616c3aa36f029130e7fa39/plugin/core/sessions.py#L1859-L1869

The problem is that such URI specific settings must explicitly be requested by the server, the client can only notify about a single `settings` object in `workspace/didChangeConfiguration`.

I've tested with pyright, and it seems to use the URI of the workspace folder for the `scopeUri` in this request after the server initializes (which according to my understanding should even be a violation of the LSP specs, because it is not a DocumentUri), and it doesn't send another URI-specific `workspace/configuration` request after a file is opened (`textDocument/didOpen`).
For example
```
:: [21:02:57.761] <-- LSP-pyright workspace/configuration (0): {'items': [{'scopeUri': 'file:///C:/Users/jwortmann/AppData/Roaming/Sublime%20Text/Packages/LSP', 'section': 'python'}]}
```

 So even if we implemented support for `scopeUri` (with the question still open how it can be integrated in the user settings), it would likely not work, at least for pyright.
