### ISSUE TITLE
Disabling/Uninstalling the package resets Sublime Text's color scheme

### ISSUE THREAD

**Issue by jsmrcaga** [sublimelsp/LSP#2414]
**Describe the bug**

The LSP package stopped working for me (not sure why), so I decided to Disable it from the command palette and re-enable it to restart it.
As I disabled it my Sublime Text config changed themes, from Monokai to Mariana, effectively changing my personal settings file.

**To Reproduce**

0. Have Package Control & LSP installed
1. Set your Sulbime Text's color scheme to something else than Mariana
2. Open the command palette (cmd + shift + p)
3. Search for: "Package Control: Disable Package" and select it (press enter)
4. Search for "LSP" and select it (press enter), effectively disabling it
5. Validate that Mariana has been set as the theme and that your personal settings file reflect this change

**Expected behavior**

LSP should be disabled without changing any other settings to the editor.

**Environment (please complete the following information):**

- OS: maxOs Sonoma 14.3
- Sublime Text version: 4169
- LSP version: 1.27.0
- Language servers used: lsp-typescript

Thank you!

**Comment by rchl** [comment]
Try disabling some other package and see if it's still reproduces. If so then I'd expected this to be more in realm of Package Control.

**Comment by jwortmann** [comment]
I doubt that it's LSP what causes this behavior (I also can't reproduce here). If LSP would modify the color scheme setting, there should be the string `color_scheme` (name of the setting) somewhere in the code. There are only two places which certainly look unrelated: https://github.com/search?q=repo%3Asublimelsp%2FLSP%20color_scheme&type=code

**Comment by jwortmann** [comment]
I actually could reproduce it if I set the color scheme to Monokai initially (I had my own color scheme configured before, and then the bug doesn't happen). But I agree that this must be caused by Package Control. If you simply add "LSP" to the "ignored_packages" setting in *Preferences.sublime-settings*, it doesn't happen. We do have some supplementary files for the default color scheme included in this package (https://github.com/sublimelsp/LSP/tree/main/ColorSchemes), but there shouldn't be any reason how that could change the user's color scheme setting when the package gets disabled.

**Comment by jsmrcaga** [comment]
Thank you for all your answers! 

I later had to update the LSP package and had the same thing happening (Monokai -> Mariana), but a second or so later it re-set to Monokai.

Thank you for the links to package control, it makes sense that this would happen if a package had or merged themes, I opened the issue here because I could not reproduce with any other package I have installed. In any case, a simple reset of the config file is enough to come back to my original color scheme.

Thanks again, I'll be marking the issue as closed.
