### ISSUE TITLE
Support list of commands, provided by language servers

### ISSUE THREAD

**Issue by istudyatuni** [sublimelsp/LSP#2471]
**Is your feature request related to a problem? Please describe.**

Language servers often informs client about some supported commands, but it seems that this is not supported here

**Describe the solution you'd like**

LSP will show list of commands, that I can run

**Describe alternatives you've considered**

Not implement it (bad)

**Additional context**

`executeCommandProvider` is one of the [server capabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverCapabilities)

**Comment by jfcherng** [comment]
I doubt that even they get listed, there is no general arguments to provide those commands since every of them are custom to the server implementation.

**Comment by istudyatuni** [comment]
Sorry, I wasn't clear enough, I mean to list and execute them. Listing without execution is indeed useless

**Comment by jfcherng** [comment]
I don't think it's fundamentally feasible. (knowing arguments for any server's commands)

**Comment by istudyatuni** [comment]
Hmm, after a closer reading of the spec (searching for word "command" :grin:) it seems that yes, commands can be know when requesting codelens actions or for inlay hints, and this is already possible. Thanks for your answers!

**Comment by jwortmann** [comment]
If you turn on debug logging (`"log_debug": true` in the LSP settings), the command names are printed to the console when the language server starts:

```
LSP: julia: Supported execute commands: ['UpdateDocstringSignature', 'CompareNothingWithTripleEqual', 'AddDocstringTemplate', 'FixMissingRef', 'ReexportModule', 'ReplaceUnusedAssignmentName', 'ExpandFunction', 'RewriteAsRawString', 'ExplicitPackageVarImport', 'DeleteUnusedFunctionArgumentName', 'OrganizeImports', 'AddLicenseIdentifier', 'RewriteAsRegularString']
```

But as pointed out by @jfcherng, it is impossible to provide a generic way to run those commands, because LSP cannot know which arguments they require. Sometimes the arguments are described in a Readme or documentation for the language server, but sometimes you must even search in the server's source code for it.
