### ISSUE TITLE
Exception on setting change

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#2554]
Got this one on changing a setting and closing a window:

```
Traceback (most recent call last):
  File "/Users/rafal/Library/Application Support/Sublime Text/Packages/LSP/plugin/core/windows.py", line 567, in _on_userprefs_updated_async
    for wm in self._windows.values():
RuntimeError: dictionary changed size during iteration
```

`self._windows` must have changed from the main thread while this code was running.

**Comment by lattaai6** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the _on_userprefs_updated_async method to use a copy of the dictionary values to avoid the RuntimeError when the dictionary size changes during iteration.

You can review changes in this commit: https://github.com/lattaai6/sublimelsp-LSP-2554/commit/839f95887e906e823c05bab16b7b7940c7e1cebe.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by jwortmann** [comment]
It looks that `self._windows` gets modified from the main thread via
https://github.com/sublimelsp/LSP/blob/2f37a49968c4591b0df9814561f65890cedb70ed/boot.py#L226-L227
which calls
https://github.com/sublimelsp/LSP/blob/2f37a49968c4591b0df9814561f65890cedb70ed/plugin/core/windows.py#L561-L562

So it should not be iterated on the async thread. Should be easy to fix.
