### ISSUE TITLE
Can't install LSP without Package Control on Mac Silicon

### ISSUE THREAD

**Issue by ondohotola** [sublimelsp/LSP#2562]
Is there a way of manually installing LSP?

I have this running with tinymist on Intel, but as Package Control requires OpenSSL 1.1 which is not available (on Silicon 15.1) I can't install it.

If someone had a recipe what steps I must do to install LSP with all dependencies (manually) I'd greatly appreciate it.

**Environment (please complete the following information):**

- OS: Mac OS X 15.1 on Silicone
- Sublime Text Build 4180
- can not run `Package Control:` on Silicon (4.0.0)
- Language servers used: trying to uses tinymist

**Additional context**

It is well know that Package COntrol requires OpenSSL1.1 which is no longer available for/on the Mac 15.1. The author of PC seems to have disappeared with the credentials to upload a new version.

It all works very well on Intel 15.1.1

**Comment by jwortmann** [comment]
Have you tried to manually install the latest version of Package Control? See the "Solution" section in the opening post at https://github.com/wbond/package_control/issues/1612

I'm not exactly sure how you could manually install the dependencies without Package Control. The currently required dependencies for LSP are listed in https://github.com/sublimelsp/LSP/blob/main/dependencies.json and it should be possible to find the corresponding links in https://github.com/packagecontrol/channel/blob/main/repository.json. Those are links to `.whl` (wheel) files. Probably it is possible somehow to manually extract them with pip, but I haven't done that before. On my Windows PC the installation directory seems to be under `AppData\Roaming\Sublime Text\Lib\python38`.

**Comment by ondohotola** [comment]
yes, tried everything, but manual.

**Comment by jwortmann** [comment]
I'll close this as there is not enough information given in the response, and because this is not really an LSP issue. In general, package dependencies are not intended to be installed manually, so the only official way to install LSP is using Package Control. If the steps from the "solution" description that I've linked above don't work, please open a new issue at the Package Control repo: https://github.com/wbond/package_control/issues
In that case a screenshot or a screen recording might help you to convince people that you really followed the given steps and it still doesn't work.

**Comment by ondohotola** [comment]
thank you
