### ISSUE TITLE
autocomlete doesn't work with ruby solargraph

### ISSUE THREAD

**Issue by foreverqihe** [sublimelsp/LSP#387]
* OS and language server: windows & solargraph
* How you installed LSP (Package Control or from git?): git and satisfy dependencies
* Minimal reproduction steps
open any ruby file, and input a string variable 'a', and then 'a.ca', it should suggest 'capitalize!'. But this is what I got: vs code can suggest 'capitalize!' on the same computer.
![image](https://user-images.githubusercontent.com/2378002/43465302-698db8ec-9520-11e8-9795-7ca33d1910e1.png)

* Log (trimmed)
LSP:  --> textDocument/didChange
LSP: socket send
SublimeLinter: WARNING: Waited in queue for 1.78s
LSP:  --> textDocument/didChange
LSP: socket send
LSP:  --> textDocument/completion
LSP: socket send

**Comment by tomv564** [comment]
Hi, thanks for sharing your issue and some logs. I've removed the unneeded "socket send" entries in your logging first. 

The `log_payloads` LSP setting would help us see what the actual reply is from the language server.

What is the version of your solargraph gem? Reading https://github.com/castwide/solargraph/issues/37, a user reported features breaking (because LSP doesn't use dynamic registration).
