### ISSUE TITLE
LSP needs a LspJumpBackCommand

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#480]
When executing LSP goto definition, 
and then executing the built in `jump_back` command, 
the cursor won't be placed in the previous place, as I expect.

To fix this, we can introduce a `LspJumpBackCommand`.
We can do the same thing as TernForSublime [did](https://github.com/ternjs/tern_for_sublime/blob/91a27a39b1b0a33a9043aa685e1ee48c64a58274/tern.py#L564).

**Comment by predragnikolic** [comment]
`ctrl+shift+d` - Lsp `lsp_symbol_definition` command.
`ctrl+shift+s` - Sublime built in `jump_back` command.

> Where is the cursor currently restored to when jumping back? 

![recorded](https://user-images.githubusercontent.com/22029477/50398864-4aded480-077b-11e9-81ef-46a85304ee0e.gif)

The jump_back command doesn't keep track that we did a lsp_symbol_definition.

Solution
Create a `LspJumpBackCommand` that would pop from `jump_back_history_stack` and  append to it when we trigger `lsp_symbol_definition`.

**Comment by tomv564** [comment]
I'd really really like to figure out how to make this work with Sublime's built-in `jump_back` instead of Tern's solution - this adds complexity to us (managing our own stack) and the user (_two_ ways to jump back).

In these release notes the jump back feature should specifically work with `goto_definition`. 
https://www.sublimetext.com/blog/articles/sublime-text-3-beta-3019

Looking at sublime's built-in python code, I found some special handling for `goto_definition` here: 
https://github.com/twolfson/sublime-files/blob/d5f4835f43a9822a59e19d6bce26a5b2fd41273c/Packages/Default/history_list.py#L203

Can our solution be inspired by that instead? Is there a "published API" way to push a selection to the stack in our own `lsp_symbol_definition` ?

**Comment by predragnikolic** [comment]
And you are right.
Here is the minimal code I could come up with for this to work
```python
from Default.history_list import get_jump_history_for_view

class LspSymbolDefinitoionListener(sublime_plugin.ViewEventListener):
    def on_text_command(self, command_name, args):
        if command_name == 'lsp_symbol_definition':
            if not self.view.settings().get('is_widget'):
                get_jump_history_for_view(self.view).push_selection(self.view)
```

**Comment by tomv564** [comment]
Nice, perhaps LspSymbolDefinitionCommand can take care of this? Want to do a PR?

**Comment by predragnikolic** [comment]
Done :) sorry for the wait
Apparently I just need one line for this. No need for a `on_text_command` listener.
