### ISSUE TITLE
Enabling Intelephense

### ISSUE THREAD

**Issue by JoyceBabu** [sublimelsp/LSP#864]
I see two options for integrating with Intelephense.

Documentation for LSP-intelephense says

>  Install LSP and LSP-intelephense from Package Control.

This enables, LSP-Intelephense on the status bar.

The *Getting Started* section of this project says

> Enable the server by running LSP: Enable Language Server from the command palette.

When selecting the option `LSP: Enable Language Server Globally`, I don't see `LSP-intelephense`. Instead `intelephense-ls` is listed. Selecting `intelephense-ls` adds `intelephense-ls` to my status bar.

Why are there two different options? Which is the official way for enabling intelephense server?

**Comment by jwortmann** [comment]
Both options should work. The `intelephense-ls` entry has probably been there to apply default configurations for the server, when the LSP-intelephense package didn't exist yet. I would say there is no "official way", but LSP-intelephense might be the preferred option here, because it can automatically install and update the server (I think) through Package Control. (I don't use that server myself though.)

**Comment by jfcherng** [comment]
Another reason to use `LSP-intelephense` is you can use variables in its `initializationOptions`.

https://github.com/sublimelsp/LSP/pull/709#issuecomment-536229131

**Comment by JoyceBabu** [comment]
Thank you for the clarification.
