### ISSUE TITLE
gopls: go to defnition does not work if not started in package's root directory

### ISSUE THREAD

**Issue by RafalSkolasinski** [sublimelsp/LSP#883]
### OS and language server
Ubuntu and gopls

### How you installed LSP (Package Control or from git?)
Package Control

### Minimal reproduction steps
Working:
1. Start subl from terminal with `subl FOLDER/WITH/go.mod -n`
2. Go to definition does work, as expected

Not working:
1. Start subl from terminal providing parent directory to above
2. Go to definition does **NOT** work at all

### Log
What logs?

**Comment by rwols** [comment]
It sounds as if this problem is similar to the Flow language server. That language server wants its rootUri to be a folder where a .flowconfig is present, and crashes if no .flowconfig file is present in the rootUri.

Flow users can account for this by creating a .sublime-project file with the following structure:

```js
{
    "folders":
    [
        {
            "path": "."  // your root folder
        },
        {
            "path": "FOLDER/WITH" // the folder with go.mod
        }
    ],
    "settings":
    {
        // ... view settings
    }
}
```

Whether gopls is workspace-aware or not does not matter if you don't have .go files outside your `FOLDER/WITH` folder.

You can use the "Project" menu entry at the top of Sublime Text to add folders to your project and save your project.

Let us know if this solves your problem!

**Comment by RafalSkolasinski** [comment]
Hi @rwols! 

Thanks a lot for the explanation. I think following your suggestion I managed to achieve something similar by starting sublime with:
```
subl . ./go-project-folder -n
```
when being in the parent directory to the `go-project-folder` containing `go.mod` file.

It seems to work fine. Also just noticed that `Project -> Save Project As...` creates similar setting to what you suggested.

Thanks a lot again! Maybe it is worth to add short note in docs about it?
