### ISSUE TITLE
[AC] AC not showing up with a "decorated" trigger

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#935]
Note: check if only DYNAMIC_COMPLETIONS are affected.

When I supplement the completion by typing more characters, the completion widget goes away.

![Peek 2020-03-28 13-19](https://user-images.githubusercontent.com/2431823/77822869-db326480-70f6-11ea-82fa-207d26bdb433.gif)
<hr>
I don't get a completion widget at all sometimes. In the gif below I expect to at least see a completion for the "time" variable:

![Peek 2020-03-28 13-31](https://user-images.githubusercontent.com/2431823/77823050-76780980-70f8-11ea-806a-009f3d56e58a.gif)

I'm guessing this is due to incomplete completions. I'm not sure what the dynamic is here.

_Originally posted by @rwols in https://github.com/sublimelsp/LSP/pull/866#issuecomment-605441312_

**Comment by rwols** [comment]
As it turns out this is due to clangd putting a space in the label. We can remove the space with the command-line option `--header-insertion-decorators`.

With `--header-insertion-decorators=0`: (looks like there's a bug in the insertion logic)

![Peek 2020-04-04 15-57](https://user-images.githubusercontent.com/2431823/78452741-582c8380-768d-11ea-84b2-e38a92567d39.gif)

Without `--header-insertion-decorators=0`:

![Peek 2020-04-04 15-58](https://user-images.githubusercontent.com/2431823/78452765-7eeaba00-768d-11ea-8927-4783eeca8c75.gif)

Currently, we're mapping the `label` of an LSP completion item to the `trigger` of a sublime completion item. But as can be seen with clangd, this is wrong.

As I mentioned way back, the concept of `trigger` in SublimeText seems to map better to the `filterText` of an LSP completion item. However, that makes the completions look a bit bare.

This is with `trigger=item["label"]` and `--header-insertion-decorators=0`:

![Peek 2020-04-04 16-27](https://user-images.githubusercontent.com/2431823/78453358-74caba80-7691-11ea-8125-0b36451fefb5.gif)

This is with `trigger=item.get("filterText") or item["label"]` and `--header-insertion-decorators=0`:

![Peek 2020-04-04 16-28](https://user-images.githubusercontent.com/2431823/78453367-785e4180-7691-11ea-85cc-9fcf518a8825.gif)

What we need is a distinction between **label** and **trigger** in SublimeText. cc @jskinner

**Comment by predragnikolic** [comment]
I wonder if "autocomplete_preserve_order": "none" would help in this case?

**Comment by rwols** [comment]
Indeed, setting auto_complete_preserve_order to "none" seems to fix the problem.

![Peek 2020-04-04 17-01](https://user-images.githubusercontent.com/2431823/78454052-eefd3e00-7695-11ea-925b-af9d9da1e166.gif)

Based on this I am inclined to say that we should put `self.view.settings().set("auto_complete_preserve_order", "none")` in completion.py.

Still, what the user sees in the AC widget, and what the user is expected to type to trigger the completion are two different concepts.

**Comment by rwols** [comment]
After googling about `filterText` I cannot find much information about it other than "it is filter text".
I thought that `filterText` would be a substring of `label`, but some language servers actually seem to be making the `label` a substring of the `filterText`. Some language servers decide that there's no substring relation between `filterText` and `label` at all. At this point I'm beginning to wonder what the point of `filterText` is or whether it is just a vscode implementation detail leaking into the protocol.

**Comment by rwols** [comment]
Fixed by #945

**Comment by jskinner** [comment]
A bit late here, but FWIW:

* `"auto_complete_preserve_order": "some"` (the default) is more aggressive about filtering out matches  than `"none"`, and part of this is that the first character of the trigger must match a character in buffer.

* Sublime Text doesn't have a notion of separate filter text vs label text. I'm not sure how that could even work: the user selects the text they want inserted by typing part of what they can see, and we bold the matched characters. If the filter text is "foo", and the label text is "bar", it would be nonsensical.
