### ISSUE TITLE
Completions on function name

### ISSUE THREAD

**Issue by quangbuule** [sublimelsp/LSP#954]
Currently we are having completions on function call and it works greatly.
Like this example (I am using Flow).
```js
const handler = (a: string, b:string) => {};
hand|
  [handler   (a: string, b:string) => {}]
```
When hitting Enter, it becomes
```js
const handler = (a: string, b:string) => {};
handler(a, b);
```

However, in the case that we only need the function name, it would be a bit clumsy. Like if I want the handler function name to be auto completed inside wrap call like this:
```js
const handler = (a: string, b:string) => {};
const wrapped = wrap(handler);
```

But actually the auto completion gives me this:
```js
const handler = (a: string, b:string) => {};
const wrapped = wrap(handler(a, b));
```
which is unexpected.

I tried the same situation on VSCode, turn out the auto completion only helps the function name, not the function call, which is I think better for my usage.

IMO, It's not harmful to do autocompletion on function name only, because after having the function name completed, you can open the parenthesis to get the hint how to call the function, which is good enough. I don't really want the full function call in the completion.
![image](https://user-images.githubusercontent.com/5992964/78726781-3590b800-7976-11ea-9a88-75e617c31187.png)

I think a configuration for whether the LSP should autocomplete the function call, or just function name will be the best.

**Comment by rwols** [comment]
Thanks for the investigation. This LSP plugin does things a bit differently than VSCode by being entirely general-purpose, requiring only a few lines of JSON configuration for straightforward language servers (much like coc-nvim). So the only thing we can do in a general sense is to take the completion items from any language server as-is and put it in your SublimeText view.  For instance, a C++ language server called clangd allows returning completion items in two different formats, depending on what you want. A Python language server called pyls does precisely what you describe: for functions it does not insert a snippet, but rather inserts only the function-name. The user has to type the parentheses him- or herself. So, my suggestion in these kind of cases is to modify the source code of the flow language server and then make a pull-request for the flow language server. That way, everybody benefits. Including emacs-lsp and coc-nvim.

**Comment by quangbuule** [comment]
After spending some times on the LSP log, I find that the TypeScript lang server doesn't returning "insertText" whereas the Flow one does. (I am not having Python dev env then I guess `pyls` would do the same with TypeScript lang server).

And in our completion plugin, it will fallback into `trigger` (which is function name) if the `insertText` (snippet for function call) is not found. Which results in the fact that I prefer how LSP handles TypeScript than the way it handles Flow.

```python 
replacement = text_edit_text(item, word_col) or item.get("insertText") or trigger
```

I think that providing the option in our plugin is better than in flow language server (which is currently maintained under the official [Flow](https://github.com/facebook/flow)).

I think something like this can be good to go:
```python
replacement = text_edit_text(item, word_col) or settings.should_complete_function_calls item.get("insertText") or trigger
```

**Comment by quangbuule** [comment]
FYI: https://github.com/facebook/flow/pull/7518

**Comment by quangbuule** [comment]
@rwols This is how VSCode handles completion:

![image](https://user-images.githubusercontent.com/5992964/79079620-93951500-7d53-11ea-9031-1b05bda0eae4.png)

So, I think VSCode is not having this as to serve general-purpose, it's configurable.

**Comment by rwols** [comment]
If you're talking about [this project](https://github.com/jstwister/vscode-flow-ide), I am again saying that it is a package tailored to the Flow language server. This package is *not tailored* for the Flow language server.

Your pull request https://github.com/sublimelsp/LSP/pull/966 introduces a setting that will apply to *all* language servers. That is not the mission or philosophy of this package. But even if you were to introduce a server-specific boolean setting, I would still not agree with the changes. Because at some point, the maintainers of the Flow language server might decide to change the `label` to something else. We've been through this before:
- Attempting to use `filterText` for the label. This used to be a workaround for textEdits/insertText/labels in clangd. Bad idea and we reverted it.
- Attempting to blacklist windows when a lang server didn't start. This used to be a workaround for Flow. Bad idea and we reverted it. 

I get that OCaml is a daunting language if you've never programmed in it before, but if you really want bare functions names to be inserted into your text buffer via the Flow language server, you will have to modify the code of Flow and add a command-line setting there. Or add it to the `initializationOptions` of the Flow language server. Or add it to the `settings` retrieval of the Flow language server. There are many points of configuration adjustment based solely on the LSP spec, and this package already handles all that.

**Comment by predragnikolic** [comment]
@quangbuule, lucky for you, someone already committed a fix for your problem 24days ago :)
https://github.com/facebook/flow/commit/774c7c7af3bb2df0c4337999720464ef8ee9aacf

**Comment by quangbuule** [comment]
Thanks heaps for the explanation @rwols :)!
@predragnikolic Haha that's so good, I just found out this morning too.

**Comment by quangbuule** [comment]
It's quite challenging on my team project because upgrading Flow is not straightforward for big project. The guy on Flow discord recommend if I used VSCode, I would like to use the `flow.useCodeSnippetOnFunctionSuggest` setting.

**Comment by predragnikolic** [comment]
@quangbuule until the flow language server doesn't make a release with the commit that will solve your problem,
the only thing I can suggest you now is to just modify this line to `false` in LSP source code on your PC.

https://github.com/sublimelsp/LSP/blob/131c8f1d5c966cb1315e61dd52cdb95b468bfda7/plugin/core/sessions.py#L35

I don't think that sublime LSP as a client should handle this specific language server case. 

Ideally the language server would have a `useCodeSnippetOnFunctionSuggest` `"initializationOptions"` that would allow a user to decide weather to insert snippets or not,
but I haven't found that in the flow language server source code.
