### ISSUE TITLE
textDocument/hover popup support navigable paths

### ISSUE THREAD

**Issue by genericptr** [sublimelsp/LSP#988]
The default hover popup allows paths to be clicked on which navigate to the source file at the given line (see picture). The LSP textDocument/hover popup overrides the default popup but does not navigate to files when clicked on. LSP should provide similar behavior to what is default for ST.

![Uploading Screen Shot 2020-04-26 at 1.46.03 PM.png…]()

**Comment by rwols** [comment]
Can you clarify a bit what you want here?

- Should LSP try to cooperate with ST's own hover popup?
- Or do you want LSP to support the `file://` schema returned from a server's hover content and jump to the file with a hyperlink instead of opening a tab in a browser?

Cooperating with ST's own hover popup is impossible. There's no API for that.

**Comment by genericptr** [comment]
![Uploading Screen Shot 2020-05-09 at 8.13.31 PM.png…]()

**Comment by predragnikolic** [comment]
I don't think that the LSP plugin should parse the hover popup content to discover all possible file like urls and make them clickable. 
If you want to go to the definition you can use the `Declaration | Implementation | References` links. :) 

The reason on why I think that we should not parse the content is the following:
Different language servers might represent the file path and the exact row col position on different unstandardized ways. For you concrete example the pascal server represent it like `/user/some/file.pas(row, col)`, some other language server might do  `../file.pas|row:col`. I am not saying that it is impossible, I just can't see a way to write a piece of code that will parse urls and work on all language servers :)

**Comment by rchl** [comment]
If this is about parsing the content provided by `textDocument/hover` then I agree that we shouldn't parse it as it's unstructured content.

Servers don't usually put links in those places anyway because they provide a location through "go to definition" (and friends). And if they put links, they can format them themselves as it's markdown.

**Comment by genericptr** [comment]
> And if they put links, they can format them themselves as it's markdown.

Are links possible in minihtml now? I may not have known this when I made the issue. In that case I agree we should use proper html links (when the editor is ST anyways).

**Comment by rchl** [comment]
Links were always possible but I guess you rather mean "links that can open files within the editor". That I'm not sure. If the path is an URI (`file://...`) then I think it should work. Unless we override the "navigate" handler and prevent that from working.

**Comment by jwortmann** [comment]
Links to files in Markdown content for popups do work for me, and I can see from the server log that `file://...` isn't even necessary. Just a normal Markdown link with the full file path is enough (at least on Windows, e.g. `C:\\path\\to\\file.txt`). There is no difference from what the built-in popups and minihtml popups from packages can do, because both use the same API.

References to line numbers should be possible too, and I think we already have the required code for it in the [on_hover_navigate](https://github.com/sublimelsp/LSP/blob/e7dac40247d68398fc24d1b19b1565d05e472ae8/plugin/hover.py#L251) function in `hover.py`.  ST's default popups seem to use the format `filepath:row:col` in href attributes (can be seen in the file `Default/symbols.py`). But I haven't tested this with language servers, since the server I use doesn't send these values for file links in popups.

I also think that the LSP package should not do additional parsing for popup contents, because it already works out of the box when formatted correctly.

**Comment by rchl** [comment]
if you have more specific case that doesn't work then please feel free to report separately
